import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';
// Explicit allowlist. No production connection/provider/whole migration replay.
const migration=readFileSync(new URL('../supabase/migrations/20260906220000_allow_bound_smartstore_local_create_claim.sql',import.meta.url),'utf8');
const baseline=readFileSync(new URL('./fixtures/aside-local-claim-220000-baseline.sql',import.meta.url),'utf8');
const old=migration.match(/\$old\$([\s\S]*?)\$old\$/)[1], replacement=migration.match(/\$new\$([\s\S]*?)\$new\$/)[1];const digest=s=>createHash('sha256').update(s).digest('hex');
test('exact live source candidate applies, repeats, refuses drift and rolls back',async()=>{const db=new PGlite();try{await db.exec('create schema sellerpilot_private');await db.exec(baseline);const get=async()=> (await db.query("select pg_get_functiondef('public.sellerpilot_11820_claim_gateway_unsafe(text,text)'::regprocedure) s")).rows[0].s;assert.equal(await get(),baseline);assert.equal(baseline.split(old).length,2);await db.exec(migration);assert.equal(await get(),baseline.replace(old,()=>replacement));await db.exec(migration);assert.equal(await get(),baseline.replace(old,()=>replacement));await db.exec(baseline.replace('v_job_id uuid;','v_job_id  uuid;'));await assert.rejects(db.exec(migration),/SOURCE_DRIFT/);await db.exec('rollback');await db.exec(baseline);assert.equal(digest(await get()),digest(baseline));}finally{await db.close()}});
const id={job:'66147e5d-0479-4c51-896e-97e782af99e1',attempt:'0d2c492e-2025-4717-bb3f-0fd2b886fd4f',product:'1ed4acfc-7603-48ec-a638-241131e59358',imp:'08acb37f-7ed0-40b0-8fb3-4a217a7ac912',token:'02955cb4-fa9f-466b-824f-b61f06276190',owner:'11111111-1111-4111-8111-111111111111',creator:'22222222-2222-4222-8222-222222222222',cred:'33333333-3333-4333-8333-333333333333',ai:'44444444-4444-4444-8444-444444444444'};const hash='a'.repeat(64),req='8f1ebe5d61834100351b96385d84f063f39b329e7e68b9b255abb286caf056f2';const stamp='2026-09-06T03:19:01.757195Z';
async function fixture(){const db=new PGlite();await db.exec(`create schema sellerpilot_private;
create table sellerpilot_private.ai_cli_worker_tokens(id uuid,token_hash text,scope text,status text,expires_at timestamptz);
create table sellerpilot_private.channel_credentials(id uuid,channel text,environment text,status text,created_by uuid,expires_at timestamptz,seller_account_key text);
create table sellerpilot_private.channel_gateway_jobs(id uuid,attempt_id uuid,channel text,operation text,environment text,status text,attempt_count int,started_at timestamptz,provider_mutation_started_at timestamptz,worker_token_id uuid,claim_token uuid,lease_expires_at timestamptz,request_payload jsonb,created_by uuid,seller_account_key text,credential_id uuid,request_fingerprint text);
create table sellerpilot_private.channel_operation_attempts(id uuid,owner_id uuid,credential_id uuid,channel text,operation text,status text,remote_id text,request_fingerprint text);
create table sellerpilot_private.products(id uuid,owner_id uuid,external_detail_import_id uuid,detail_page_version int,updated_at timestamptz,ai_job_id uuid);
create table sellerpilot_private.external_detail_imports(id uuid,owner_id uuid,status text,approved_detail_version int,approved_product_updated_at timestamptz,request_sha256 text,payload jsonb,receipts jsonb);
create function sellerpilot_private.listing_mutation_release_gate_is_effective(text) returns boolean language sql as $$select coalesce(current_setting('fixture.gate',true),'open')='open'$$;
insert into sellerpilot_private.ai_cli_worker_tokens values('${id.token}','fixture-token','gateway','active',now()+interval '1 day');
insert into sellerpilot_private.channel_credentials values('${id.cred}','smartstore','production','active','${id.creator}',null,'seller');
insert into sellerpilot_private.channel_operation_attempts values('${id.attempt}','${id.owner}','${id.cred}','smartstore','listing.create','running',null,'${hash}');
insert into sellerpilot_private.products values('${id.product}','${id.owner}','${id.imp}',2,'${stamp}','${id.ai}');`);
const binding={contract:'sellerpilot_external_detail_channel_v1',productId:id.product,importId:id.imp,version:2,channel:'smartstore',language:'ko',locale:'ko-KR',productUpdatedAt:stamp,requestSha256:req,documentSha256:hash,imageSha256s:Array(8).fill(hash),pixelSha256s:Array(8).fill(hash)};
await db.query('insert into sellerpilot_private.external_detail_imports values($1,$2,\'approved\',2,$3,$4,$5,$6)',[id.imp,id.owner,stamp,req,JSON.stringify({expectedAiJobId:id.ai,reviewedCopy:{ko:{documentSha256:hash}},assets:Array(8).fill({sourceSha256:hash})}),JSON.stringify(Array(8).fill({decodedRgbaSha256:hash}))]);
await db.query("insert into sellerpilot_private.channel_gateway_jobs values($1,$2,'smartstore','listing.create','production','queued',0,null,null,null,null,null,$3,$4,'seller',$5,$6)",[id.job,id.attempt,JSON.stringify({arguments:{publicationIntent:'live',publicationExpectedLocale:'ko-KR',sellerpilotExternalDetail:binding}}),id.creator,id.cred,hash]);
const predicate=replacement.replace(/^\s*and /,'').replaceAll('v_token_id',`'${id.token}'::uuid`).replaceAll('p_worker_version',"current_setting('fixture.version',true)").replaceAll('p_token_hash',"'fixture-token'");await db.exec("set fixture.version='sellerpilot-cli-worker/1.60'");
await db.exec(`alter table sellerpilot_private.channel_gateway_jobs add prepared_credential_id uuid, add created_at timestamptz default now(), add completed_at timestamptz, add updated_at timestamptz, add credential_refresh_in_flight boolean default false, add credential_refresh_recovery_vault_id uuid, add oauth_exchange_completed boolean default false;
alter table sellerpilot_private.channel_credentials add last_check_status text, add last_checked_at timestamptz;
create function sellerpilot_private.serverless_gateway_job_allowed(text,text) returns boolean language sql as $$select false$$;
create function sellerpilot_private.qoo10_shipping_s1_verifier_job_matches(sellerpilot_private.channel_gateway_jobs) returns boolean language sql as $$select false$$;
create function sellerpilot_private.qoo10_shipping_s1_activation_job_matches(sellerpilot_private.channel_gateway_jobs) returns boolean language sql as $$select false$$;
create function sellerpilot_private.qoo10_shipping_s1_activation_claim_priority(uuid) returns boolean language sql as $$select false$$;
create function sellerpilot_private.qoo10_exact_s1_activation_claim_priority(uuid) returns boolean language sql as $$select false$$;`);
const patched=baseline.replace(old,()=>replacement);
const start=patched.indexOf('  select j.id into v_job_id');const end=patched.indexOf('  if v_job_id is null',start);
const eligible=patched.slice(start,end).trim().replace('select j.id into v_job_id','select j.id').replace(/;$/,'').replaceAll('v_token_id',`'${id.token}'::uuid`).replaceAll('p_worker_version',"current_setting('fixture.version',true)").replaceAll('p_token_hash',"'fixture-token'");
return {db,eligible,check:async()=> (await db.query(eligible)).rows.length===1};}
test('exact SQL predicate: positive, negative binding/security/version matrix',async()=>{const {db,check}=await fixture();try{assert.equal(await check(),true);const cases=[
['wrong job',"update sellerpilot_private.channel_gateway_jobs set id=gen_random_uuid()"],['wrong attempt',"update sellerpilot_private.channel_gateway_jobs set attempt_id=gen_random_uuid()"],['update excluded',"update sellerpilot_private.channel_gateway_jobs set operation='listing.update'"],['already attempted',"update sellerpilot_private.channel_gateway_jobs set attempt_count=1"],['mutation started',"update sellerpilot_private.channel_gateway_jobs set provider_mutation_started_at=now()"],['lease exists',"update sellerpilot_private.channel_gateway_jobs set lease_expires_at=now()"],['wrong owner',"update sellerpilot_private.channel_operation_attempts set owner_id=gen_random_uuid()"],['wrong credential',"update sellerpilot_private.channel_operation_attempts set credential_id=gen_random_uuid()"],['remote exists',"update sellerpilot_private.channel_operation_attempts set remote_id='remote'"],['wrong fingerprint',"update sellerpilot_private.channel_operation_attempts set request_fingerprint='wrong'"],['scope wrong',"update sellerpilot_private.ai_cli_worker_tokens set scope='serverless_cs'"],['token expired',"update sellerpilot_private.ai_cli_worker_tokens set expires_at=now()-interval '1 day'"],['token revoked',"update sellerpilot_private.ai_cli_worker_tokens set status='revoked'"],['version mismatch',"set local fixture.version='sellerpilot-vercel-gateway/2.0'"],['recovery lane',"set local sellerpilot.local_gateway_recovery_lane='enabled'"],['release closed',"set local fixture.gate='closed'"],['credential expired',"update sellerpilot_private.channel_credentials set expires_at=now()-interval '1 day'"],['seller mismatch',"update sellerpilot_private.channel_credentials set seller_account_key='other'"],['approval pending',"update sellerpilot_private.external_detail_imports set status='pending'"],['version stale',"update sellerpilot_private.products set detail_page_version=3"],['timestamp stale',"update sellerpilot_private.products set updated_at=now()"],['receipts missing',"update sellerpilot_private.external_detail_imports set receipts='[]'"],['receipts null',"update sellerpilot_private.external_detail_imports set receipts=null"],['wrong pixels',"update sellerpilot_private.external_detail_imports set receipts=jsonb_set(receipts,'{0,decodedRgbaSha256}','\"bad\"')"],['request null',"update sellerpilot_private.channel_gateway_jobs set request_payload=null"],['draft',"update sellerpilot_private.channel_gateway_jobs set request_payload=jsonb_set(request_payload,'{arguments,publicationIntent}','\"draft\"')"]];
for(const [name,sql]of cases){await db.exec('begin');await db.exec(sql);assert.equal(await check(),false,name);await db.exec('rollback');}console.log('binding matrix: 1 positive + '+cases.length+' negative cases');
for(const operation of ['diagnostic.test','categories.list','inquiries.list','listing.publication.verify']){await db.exec('begin');await db.query('update sellerpilot_private.channel_gateway_jobs set operation=$1',[operation]);assert.equal(await check(),true,'existing read '+operation);await db.exec("set local sellerpilot.local_gateway_recovery_lane='enabled'");assert.equal(await check(),true,'recovery read preserved '+operation);await db.exec('rollback');}
for(const status of ['running','reconciliation_required']){await db.exec('begin');await db.query("insert into sellerpilot_private.channel_gateway_jobs(id,credential_id,channel,environment,status,credential_refresh_in_flight,lease_expires_at) values(gen_random_uuid(),$1,'smartstore','production',$2,true,now()+interval '1 day')",[id.cred,status]);assert.equal(await check(),false,status+' sibling fence');await db.exec('rollback');}
console.log('full SELECT: 4 reads normal+recovery preserved, running/recon siblings rejected; other-channel helpers explicitly stubbed');
}finally{await db.close()}});
test('parallel submitted consumers cannot consume exact job twice on serialized PGlite connection',async()=>{const {db,eligible}=await fixture();try{const consume=`with candidate as (${eligible}) update sellerpilot_private.channel_gateway_jobs j set status='running',attempt_count=attempt_count+1 where j.id in(select id from candidate) and j.status='queued' returning j.id`;const results=await Promise.all([db.query(consume),db.query(consume)]);assert.equal(results.reduce((n,r)=>n+r.rows.length,0),1);}finally{await db.close()}});
test('routing patch changes only local write exclusion and retains original recovery, running/recon and locking text',()=>{const patched=baseline.replace(old,()=>replacement);assert.equal(patched.replace(replacement,()=>old),baseline);for(const s of ['sellerpilot.local_gateway_recovery_lane','for update of j, c skip locked',"running.status = 'running'","unresolved.status = 'reconciliation_required'"])assert.ok(patched.includes(s));assert.equal(migration.includes('183000_claim'),false);});
