import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import test from"node:test";import{PGlite}from"@electric-sql/pglite";
const migration=await readFile(new URL("../supabase/migrations/20260908003100_add_cs_recovery_drills.sql",import.meta.url),"utf8"),owner="00000000-0000-4000-8000-000000001201",digest=value=>value.repeat(64);
async function fixture(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${owner}');create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function public.sellerpilot_is_admin()returns boolean language sql stable security definer as $$select auth.uid()='${owner}'::uuid$$;create schema sellerpilot_private;`);await db.exec(migration);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);return db;}
const drills=["raw_restart","provider_429","provider_5xx","reply_timeout_unknown","token_expiry","permission_revoked","attachment_expired","backup_restore","delete_and_recollect","admin_revoked"];
async function record(db,drill,hash,at){return db.query("select public.sellerpilot_record_cs_recovery_drill_v1(null,'all',$1,'passed',$2,'{}'::jsonb,$3)",[drill,hash,at]);}
test("recovery readiness requires every drill and two distinct daily restart dates",async()=>{const db=await fixture();try{
 let read=(await db.query("select public.sellerpilot_read_cs_recovery_readiness_v1() result")).rows[0].result;assert.equal(read.ready,false);assert.equal(read.requirements.length,11);
 for(let index=0;index<drills.length;index++)await record(db,drills[index],digest((index%6+10).toString(16).slice(-1)),"2026-09-06T01:00:00Z");
 await record(db,"daily_restart",digest("7"),"2026-09-06T02:00:00Z");await record(db,"daily_restart",digest("8"),"2026-09-06T10:00:00Z");
 read=(await db.query("select public.sellerpilot_read_cs_recovery_readiness_v1() result")).rows[0].result;assert.equal(read.ready,false);assert.equal(read.requirements.find(row=>row.drill==="daily_restart").observedDistinctDays,1);
 await record(db,"daily_restart",digest("9"),"2026-09-07T02:00:00Z");read=(await db.query("select public.sellerpilot_read_cs_recovery_readiness_v1() result")).rows[0].result;assert.equal(read.ready,true);
}finally{await db.close();}});
test("drill ledger is not directly readable and service role cannot call admin evidence APIs",async()=>{const db=await fixture();try{for(const role of["anon","service_role"])assert.equal((await db.query("select has_function_privilege($1,'public.sellerpilot_read_cs_recovery_readiness_v1()','EXECUTE') ok",[role])).rows[0].ok,false);}finally{await db.close();}});
