import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
const migration=await readFile(new URL('../supabase/migrations/20260914161000_ebay_c9_confirmed_refresh_fence_reconciliation.sql',import.meta.url),'utf8');
const incident='c9d6431c-5418-4649-9542-f30137309bf4';
const source='2ba31905-9879-44c4-88be-2204776fa303';
const successor='0aca8183-7440-4076-ba0f-679c20259a81';
const queued='004aff8e-7f0c-4c8e-bff5-ac75b395b2cb';
const owner='21eb1892-0894-4f9f-b414-4c9464182dd6';
async function fixture(){
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create schema sellerpilot_private;create schema extensions;create schema vault;
 create function extensions.digest(v text,a text) returns bytea language sql immutable as $$select sha256(convert_to(v,'UTF8'))$$;
 create table vault.decrypted_secrets(id uuid primary key,decrypted_secret text);
 create table sellerpilot_private.channel_credentials(id uuid primary key,version int,status text,channel text,environment text,created_by uuid,seller_account_key text,seller_account_key_source text,seller_account_verified_at timestamptz,last_check_status text,expires_at timestamptz,vault_secret_id uuid);
 create table sellerpilot_private.channel_gateway_jobs(id uuid primary key,channel text,environment text,operation text,status text,error_message text,credential_id uuid,created_by uuid,seller_account_key text,credential_refresh_in_flight boolean,credential_refresh_started_at timestamptz,claim_token uuid,lease_expires_at timestamptz,completed_at timestamptz,provider_mutation_started_at timestamptz,prepared_credential_id uuid,credential_refresh_fingerprint text,credential_refresh_prepared_at timestamptz,credential_refresh_recovery_vault_id uuid,credential_refresh_recovery_fingerprint text,credential_refresh_recovery_staged_at timestamptz,oauth_exchange_completed boolean,request_payload jsonb,response_payload jsonb,updated_at timestamptz,
 constraint flight_check check(credential_refresh_in_flight=(credential_refresh_started_at is not null)));
 create table sellerpilot_private.credential_audit(id bigint generated by default as identity(start with 587) primary key,credential_id uuid,channel text,environment text,action text,actor_user_id uuid,safe_detail jsonb,occurred_at timestamptz default clock_timestamp());
 insert into vault.decrypted_secrets values('${source}',jsonb_build_object('provider_account_subject','fixture-exact-seller','refresh_token','fixture-only','scopes','fixture-scope','client_id','fixture-app')::text),('${successor}',jsonb_build_object('provider_account_subject','fixture-exact-seller','refresh_token','fixture-only','scopes','fixture-scope','client_id','fixture-app','access_token_expires_at',clock_timestamp()+interval '2 hours')::text);
 insert into sellerpilot_private.channel_credentials values('${source}',210,'revoked','ebay','production','${owner}',repeat('a',64),'provider_certified_v1',clock_timestamp()-interval '3 minutes','passed',null,'${source}'),('${successor}',211,'active','ebay','production','${owner}',repeat('a',64),'provider_certified_v1',clock_timestamp()-interval '30 seconds','passed',clock_timestamp()+interval '2 hours','${successor}');
 insert into sellerpilot_private.channel_gateway_jobs(id,channel,environment,operation,status,error_message,credential_id,created_by,seller_account_key,credential_refresh_in_flight,credential_refresh_started_at,completed_at,oauth_exchange_completed,request_payload,response_payload,updated_at) values
 ('${incident}','ebay','production','inquiries.list','reconciliation_required','CS_PROVIDER_RESULT_REQUIRES_RECONCILIATION','${source}','${owner}',repeat('a',64),true,clock_timestamp()-interval '3 minutes',clock_timestamp()-interval '2 minutes',false,'{"arguments":{"fixture":"original"}}',null,clock_timestamp()-interval '2 minutes'),
 ('${queued}','ebay','production','listing.create','queued',null,'${successor}','${owner}',repeat('a',64),false,null,null,false,'{"arguments":{"sku":"exact-preserved-create"}}',null,clock_timestamp()-interval '1 minute');
 insert into sellerpilot_private.credential_audit(id,credential_id,channel,environment,action,safe_detail)
 select 586,'${successor}','ebay','production','token_refreshed',jsonb_build_object('source','v210_confirmed_access_store_v1','sourceCredentialId','${source}','preservedIncidentJobId','${incident}','sameSellerGetUserVerified',true,'sameRefreshTokenAndScope',true,'providerVerifiedAt',clock_timestamp()-interval '1 minute','incidentRowSha256',encode(extensions.digest(to_jsonb(j)::text,'sha256'),'hex'),'payloadSha256',(select encode(extensions.digest((decrypted_secret::jsonb)::text,'sha256'),'hex') from vault.decrypted_secrets where id='${successor}')) from sellerpilot_private.channel_gateway_jobs j where id='${incident}';`);
 await db.exec(migration);return db;
}
const row=async(db,id)=>(await db.query('select to_jsonb(j) r from sellerpilot_private.channel_gateway_jobs j where id=$1',[id])).rows[0].r;
const call=async db=>(await db.query('select public.sellerpilot_service_reconcile_ebay_c9_confirmed_refresh() r')).rows[0].r;
test('verified v211 supersedes only obsolete refresh fields, preserves inquiry and queued CREATE, and replays once',async()=>{
 const db=await fixture();try{
  const before=await row(db,incident),pending=await row(db,queued);
  const result=await call(db);assert.equal(result.replayed,false);assert.equal(result.inquiryStatus,'reconciliation_required');
  const after=await row(db,incident);assert.deepEqual(after,{...before,credential_refresh_in_flight:false,credential_refresh_started_at:null});
  assert.deepEqual(await row(db,queued),pending);
  const audit=(await db.query("select safe_detail from sellerpilot_private.credential_audit where id<>586")).rows;
  assert.equal(audit.length,1);assert.equal(audit[0].safe_detail.oldRefreshOutcome,'unknown');assert.equal(audit[0].safe_detail.priorRefreshStartedAt,before.credential_refresh_started_at);
  assert.equal(audit[0].safe_detail.forcedProviderCalls,0);assert.equal((await call(db)).replayed,true);
  assert.equal((await db.query('select count(*)::int n from sellerpilot_private.credential_audit')).rows[0].n,2);
 }finally{await db.close();}
});
test('reconciliation rollback restores exact incident, CREATE and audit rows',async()=>{
 const db=await fixture();try{
  const before=await row(db,incident),pending=await row(db,queued);
  await db.exec('begin');await call(db);await db.exec('rollback');
  assert.deepEqual(await row(db,incident),before);assert.deepEqual(await row(db,queued),pending);
  assert.equal((await db.query('select count(*)::int n from sellerpilot_private.credential_audit')).rows[0].n,1);
 }finally{await db.close();}
});
test('missing, changed, expired, other-seller and active-provider evidence cannot clear the fence',async()=>{
 const db=await fixture();try{
 const changes=[
  'delete from sellerpilot_private.credential_audit where id=586',
  "update sellerpilot_private.credential_audit set safe_detail=jsonb_set(safe_detail,'{sameSellerGetUserVerified}','false') where id=586",
  `update sellerpilot_private.channel_gateway_jobs set provider_mutation_started_at=clock_timestamp() where id='${incident}'`,
  `update sellerpilot_private.channel_gateway_jobs set response_payload='{"changed":true}' where id='${incident}'`,
  `update sellerpilot_private.channel_credentials set expires_at=clock_timestamp()-interval '1 minute' where id='${successor}'`,
  `update sellerpilot_private.channel_credentials set seller_account_key=repeat('b',64) where id='${successor}'`,
  `update vault.decrypted_secrets set decrypted_secret=jsonb_set(decrypted_secret::jsonb,'{provider_account_subject}','"other-seller"')::text where id='${successor}'`,
  `update sellerpilot_private.channel_gateway_jobs set status='running' where id='${queued}'`,
 ];
 const before=await row(db,incident);
 for(const change of changes){await db.exec('begin');await db.exec(change);await assert.rejects(call(db),/EBAY_C9_/);await db.exec('rollback');assert.deepEqual(await row(db,incident),before);}
 }finally{await db.close();}
});
test('only service_role can execute the exact-incident reconciler',async()=>{
 const db=await fixture();try{
 for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("select has_function_privilege($1,'public.sellerpilot_service_reconcile_ebay_c9_confirmed_refresh()','EXECUTE') allowed",[role])).rows[0].allowed,role==='service_role');
 }finally{await db.close();}
});
