import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
import{fixture}from'./external-detail-import-db.test.mjs';import{externalDetailDigest}from'../lib/external-detail-copy.ts';
const owner='11111111-1111-4111-8111-111111111111',product='1ed4acfc-7603-48ec-a638-241131e59358',id='22222222-2222-4222-8222-222222222222',job='33333333-3333-4333-8333-333333333333',source='44444444-4444-4444-8444-444444444444',attempt='55555555-5555-4555-8555-555555555555',verifier='66666666-6666-4666-8666-666666666666',listing='77777777-7777-4777-8777-777777777777',claim='88888888-8888-4888-8888-888888888888',hash='a'.repeat(64),time='2026-09-05T12:00:00.123456+00:00';
async function setup(){const db=await fixture();await db.exec(`alter table sellerpilot_private.channel_gateway_jobs add column request_fingerprint text,add column attempt_id uuid,add column listing_id uuid,add column response_payload jsonb,add column claim_token uuid,add column write_resource_kind text,add column write_resource_key text;
create table sellerpilot_private.channel_operation_attempts(id uuid primary key,owner_id uuid);
create table sellerpilot_private.marketplace_normalized_assets(object_path text primary key,content_sha256 text,status text);
create table sellerpilot_private.marketplace_normalized_asset_refs(attempt_id uuid,object_path text,upload_confirmed_at timestamptz,canonical_public_url text,source_object_path text,source_content_sha256 text,updated_at timestamptz);
create table sellerpilot_private.listing_publication_reviews(listing_id uuid,last_job_id uuid,source_job_id uuid,status text,expected_fingerprint text,expected_remote_id text,expected_locale text,market text,target_id text);
create function sellerpilot_private.serverless_cs_job_is_owned(text,uuid,uuid,boolean)returns boolean language sql as $$select $1='valid-token'$$;
create function sellerpilot_private.listing_publication_review_is_current(uuid)returns boolean language sql as $$select exists(select 1 from sellerpilot_private.listing_publication_reviews where listing_id=$1 and status='verifying')$$;
create function public.sellerpilot_service_listing_publication_verification_source(text,uuid,uuid)returns jsonb language sql as $$select '{"legacyBranch":true}'::jsonb$$;
insert into sellerpilot_private.channel_operation_attempts values('${attempt}','${owner}');`);
const old=await readFile(new URL('../supabase/migrations/20260830121000_listing_publication_verification_source.sql',import.meta.url),'utf8');
for(const name of ['public.sellerpilot_service_bind_marketplace_normalized_asset_urls','sellerpilot_private.listing_publication_asset_binding_is_current']){const pos=old.indexOf(name+'(');const begin=old.lastIndexOf('create or replace function',pos);const end=old.indexOf('$$;',pos)+3;await db.exec(old.slice(begin,end));}
await db.exec(await readFile(new URL('../supabase/migrations/20260906053000_external_detail_publication_lifecycle.sql',import.meta.url),'utf8'));return db;}
async function scalar(db,sql,params=[]){return Object.values((await db.query(sql,params)).rows[0])[0];}
async function seed(db){const roles=['detail-overview','detail-feature','detail-use','detail-package','detail-routine','detail-dimensions','detail-contents','detail-care'];const assets=roles.map((role,i)=>({assetId:`00000000-0000-4000-8000-${String(i+10).padStart(12,'0')}`,role,sourceSha256:String(i).repeat(64),byteLength:100}));assets.forEach(a=>a.storagePath=`external-detail/${owner}/${product}/${id}/${a.assetId}/${a.sourceSha256}.png`);const copies=Object.fromEntries(['ko','ja','en'].map(l=>{const document={root:{},content:[{type:'StoryBlock',props:{body:`한글 日本語 English ${l}`}}]};return[l,{document,documentSha256:externalDetailDigest(document),reviewNote:'Synthetic reviewer'}];}));
const raw={importId:id,productId:product,ownerId:owner,actorId:owner,expectedProductUpdatedAt:time,expectedDetailVersion:1,expectedAiJobId:job,source:{kind:'external_generated'},assets,originalEvidence:[{path:`${owner}/original.png`,sha256:hash}],reviewedCopy:copies};const payload={...raw,requestSha256:externalDetailDigest(raw)};const receipts=assets.map(a=>({...a,decodedRgbaSha256:a.sourceSha256,verification:'bytes_only_not_approved'}));const call=(action,p)=>scalar(db,'select public.sellerpilot_service_external_detail_import($1,$2,$3,$4,$5::jsonb)',[action,owner,product,id,JSON.stringify(p)]);await call('reserve',payload);await call('verify',{requestSha256:payload.requestSha256,receipts});const approved=await call('approve',{requestSha256:payload.requestSha256,receipts,reviewConfirmed:true});return{assets,payload,approved};}
test('SQL canonical SHA equals JS and approval mutation is rejected',async()=>{const db=await setup();try{const values=[{z:'한글 日本語',a:[1,true,null,'"\n']},{a:2,A:1},{}];for(const v of values)assert.equal(await scalar(db,'select sellerpilot_private.external_detail_hash($1::jsonb)',[JSON.stringify(v)]),externalDetailDigest(v));await seed(db);assert.equal(await scalar(db,'select sellerpilot_private.external_detail_import_is_current($1)',[id]),true);await db.exec(`update sellerpilot_private.external_detail_imports set payload=jsonb_set(payload,'{reviewedCopy,ja,document}', '{"tampered":true}')`);assert.equal(await scalar(db,'select sellerpilot_private.external_detail_import_is_current($1)',[id]),false);}finally{await db.close();}});
test('external original binds to immutable public normalized JPG, signed URL and unapproved source fail',async()=>{const db=await setup();try{const {assets}=await seed(db);const a=assets[0],content='b'.repeat(64),path=`normalized/bb/${content}.jpg`,url=`https://test.supabase.co/storage/v1/object/public/sellerpilot-marketplace/${path}`;await db.query('insert into sellerpilot_private.marketplace_normalized_assets values($1,$2,$3)',[path,content,'available']);await db.query('insert into sellerpilot_private.marketplace_normalized_asset_refs(attempt_id,object_path,upload_confirmed_at)values($1,$2,now())',[attempt,path]);const entry={objectPath:path,contentSha256:content,publicUrl:url,sourceObjectPath:a.storagePath,sourceSha256:a.sourceSha256};const bind=e=>scalar(db,'select public.sellerpilot_service_bind_marketplace_normalized_asset_urls($1,$2::jsonb)',[attempt,JSON.stringify([e])]);assert.equal(await bind(entry),true);assert.equal(await bind(entry),true);assert.equal(await scalar(db,'select source_object_path from sellerpilot_private.marketplace_normalized_asset_refs'),a.storagePath);await assert.rejects(bind({...entry,publicUrl:'https://test.supabase.co/storage/v1/object/sign/private/a?token=expires'}),/binding invalid/);await assert.rejects(bind({...entry,sourceSha256:'c'.repeat(64)}),/SOURCE_INVALID/);}finally{await db.close();}});
test('external readback source needs real normalized refs and provider receipt; legacy path delegates',async()=>{const db=await setup();try{const {assets,payload,approved}=await seed(db);const images=assets.map(a=>({role:a.role,path:a.storagePath,sourceSha256:a.sourceSha256}));const digest=createHash('sha256').update(images.map(a=>`${a.role}\t${a.path}\t${a.sourceSha256}`).join('\n')).digest('hex');
const b={productId:product,ownerId:owner,importId:id,version:2,productUpdatedAt:approved.approved_product_updated_at,requestSha256:payload.requestSha256,channel:'qoo10',language:'ja',locale:'ja-JP',documentSha256:payload.reviewedCopy.ja.documentSha256,allLocaleDocumentSha256:Object.fromEntries(Object.entries(payload.reviewedCopy).map(([l,c])=>[l,c.documentSha256])),imageSha256s:assets.map(a=>a.sourceSha256),pixelSha256s:assets.map(a=>a.sourceSha256),title:'Reviewed',html:'<p>Reviewed</p>',plain:'Reviewed',sections:[]};b.exportSha256=externalDetailDigest({title:b.title,html:b.html,plain:b.plain,sections:b.sections});
const normalized=assets.map((a,i)=>{const sha=(i+1).toString(16).repeat(64),path=`normalized/${sha.slice(0,2)}/${sha}.jpg`;return {role:a.role,approvedObjectPath:a.storagePath,approvedSourceSha256:a.sourceSha256,objectPath:path,contentSha256:sha,publicUrl:`https://test.supabase.co/storage/v1/object/public/sellerpilot-marketplace/${path}`};});for(const n of normalized){await db.query('insert into sellerpilot_private.marketplace_normalized_assets values($1,$2,$3)',[n.objectPath,n.contentSha256,'available']);await db.query('insert into sellerpilot_private.marketplace_normalized_asset_refs values($1,$2,now(),$3,$4,$5,now())',[attempt,n.objectPath,n.publicUrl,n.approvedObjectPath,n.approvedSourceSha256]);}
const binding={contract:'sellerpilot_publication_asset_binding_v1',approvedManifestDigest:digest,approvedDetailPageVersion:2,approvedDetailImages:normalized,providerTransportImages:normalized,providerImageSurface:'detail_content'};const args={sellerpilotExternalDetail:b,sellerpilotPublicationAssetBinding:binding,publicationExpectedLocale:'ja-JP',publicationExpectedFingerprint:hash};
await db.query('insert into sellerpilot_private.channel_gateway_jobs(id,created_by,channel,operation,status,request_payload,request_fingerprint,attempt_id,listing_id,response_payload)values($1,$2,\'qoo10\',\'listing.update\',\'succeeded\',$3::jsonb,$4,$5,$6,$7::jsonb)',[source,owner,JSON.stringify({arguments:args}),hash,attempt,listing,JSON.stringify({remoteState:{evidence:{publicationAssetBinding:{contract:'sellerpilot_provider_asset_binding_v1',approvedManifestDigest:digest,approvedDetailPageVersion:2,providerDetailImageIdentities:assets.map((_,i)=>'provider-'+i)}}}})]);
await db.query("insert into sellerpilot_private.channel_gateway_jobs(id,created_by,channel,operation,status,claim_token)values($1,$2,'qoo10','listing.publication.verify','running',$3)",[verifier,owner,claim]);await db.query("insert into sellerpilot_private.listing_publication_reviews values($1,$2,$3,'verifying',$4,'remote','ja-JP','JP','Japan')",[listing,verifier,source,hash]);const read=token=>scalar(db,'select public.sellerpilot_service_listing_publication_verification_source($1,$2,$3)',[token,verifier,claim]);assert.equal((await read('valid-token')).sourceJobId,source);
const manifest=await scalar(db,'select sellerpilot_private.external_detail_source_manifest($1)',[source]);const validateBinding=value=>scalar(db,'select sellerpilot_private.external_detail_asset_binding_is_current($1::jsonb,$2::jsonb,2,$3)',[JSON.stringify(value),JSON.stringify(manifest),attempt]);
assert.equal(await validateBinding({...binding,providerImageSurface:'buyer_visible'}),false,'buyer_visible is Shopee only');
const repSha='f'.repeat(64),repPath='normalized/ff/'+repSha+'.jpg',rep={role:'gallery-representative',contentSha256:repSha,objectPath:repPath,publicUrl:'https://test.supabase.co/storage/v1/object/public/sellerpilot-marketplace/'+repPath};await db.query('insert into sellerpilot_private.marketplace_normalized_assets values($1,$2,$3)',[repPath,repSha,'available']);await db.query('insert into sellerpilot_private.marketplace_normalized_asset_refs(attempt_id,object_path,upload_confirmed_at,canonical_public_url)values($1,$2,now(),$3)',[attempt,repPath,rep.publicUrl]);assert.equal(await validateBinding({...binding,providerImageSurface:'gallery',providerTransportImages:[rep,...normalized]}),true);assert.equal(await validateBinding({...binding,providerImageSurface:'gallery',providerTransportImages:[rep,...normalized.slice(0,7)]}),false);
await db.query("update sellerpilot_private.channel_gateway_jobs set status='running' where id=$1",[source]);await assert.rejects(db.query("update sellerpilot_private.channel_gateway_jobs set status='succeeded',response_payload='{}' where id=$1",[source]),/RECEIPT_REQUIRED/);await db.query("update sellerpilot_private.channel_gateway_jobs set status='succeeded' where id=$1",[source]);await assert.rejects(read('wrong-token'),/ownership/);await db.exec("update sellerpilot_private.marketplace_normalized_assets set status='missing'");await assert.rejects(read('valid-token'),/SOURCE_UNAVAILABLE/);await assert.rejects(db.query("update sellerpilot_private.channel_gateway_jobs set status='succeeded' where id=$1",[verifier]),/VERIFIER_COMMIT_STALE/);assert.deepEqual(await scalar(db,'select public.sellerpilot_service_listing_publication_verification_source($1,$2,$3)',['valid-token',job,claim]),{legacyBranch:true});}finally{await db.close();}});
