// LOCAL TEST generator only. Reproduces the reviewed wrapper guards against isolated PGlite. Never a new operating approval/application.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {realFixture,catalog as live} from './external-detail-real-publication.fixture.mjs';
import path from 'node:path';
export async function prepareExternalReviewed(outputDirectory){
const tmp=path.resolve(outputDirectory)+path.sep;
const sha=s=>createHash('sha256').update(s).digest('hex');const q=s=>"'"+s.replaceAll("'","''")+"'";
const frozen=JSON.parse(await readFile(new URL('./fixtures/external-detail-frozen-manifest.json',import.meta.url),'utf8'));
const aliases=frozen.renamed;
const tables=['products','commerce_orders','channel_credentials','channel_gateway_jobs','ai_cli_worker_tokens','gateway_completion_receipts','operation_audit','admin_users','ai_cli_jobs','channel_operation_attempts','product_listings','listing_publication_reviews','marketplace_normalized_assets','marketplace_normalized_asset_refs','product_category_assignments','inventory_product_bindings','inventory_items','inventory_ledger','inventory_reservations','inventory_sync_runs','lazada_order_item_claims','channel_market_targets','shopee_exact_oauth_sessions','lazada_exact_oauth_sessions','lazada_exact_claims','lazada_exact_completions'].map(t=>'sellerpilot_private.'+t).concat('vault.secrets','storage.objects','storage.buckets');
const fnSql=`select n.nspname||'.'||p.proname||'('||oidvectortypes(p.proargtypes)||')' signature,jsonb_build_object('bodySha256',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex'),'owner',pg_get_userbyid(p.proowner),'acl',(select jsonb_agg(jsonb_build_array(case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee)end,pg_get_userbyid(a.grantor),a.privilege_type,a.is_grantable)order by a.grantee::regrole::text,a.grantor::regrole::text,a.privilege_type)from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a),'definer',p.prosecdef,'config',p.proconfig,'language',l.lanname,'returns',pg_get_function_result(p.oid),'args',pg_get_function_arguments(p.oid),'names',p.proargnames,'volatility',p.provolatile,'parallel',p.proparallel,'strict',p.proisstrict,'leakproof',p.proleakproof,'kind',p.prokind,'retset',p.proretset) item from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname in('public','sellerpilot_private')`;
const triggerSql=`select n.nspname||'.'||c.relname tbl,case when t.tgisinternal then null else t.tgname end name,t.tgisinternal internal,t.tgenabled enabled,t.tgtype type,t.tgnargs nargs,encode(t.tgargs,'hex') args,t.tgattr::text attrs,case when t.tgqual is null then null else pg_get_triggerdef(t.oid) end qual,t.tgdeferrable deferrable,t.tginitdeferred deferred,t.tgfoid::regprocedure::text function,(select k.conrelid::regclass::text from pg_constraint k where k.oid=t.tgconstraint) constraint_table,(select k.conname from pg_constraint k where k.oid=t.tgconstraint) constraint_name,case when t.tgisinternal then pg_get_constraintdef(t.tgconstraint) else pg_get_triggerdef(t.oid) end definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('sellerpilot_private','storage','auth','vault')`;
const constraintsSql=`select n.nspname||'.'||c.relname tbl,k.conname name,k.contype type,k.convalidated validated,pg_get_constraintdef(k.oid) definition from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('sellerpilot_private','storage','auth','vault')`;
const securitySql=`select n.nspname||'.'||c.relname tbl,pg_get_userbyid(c.relowner) owner,c.relacl::text acl,c.relrowsecurity rls,c.relforcerowsecurity force_rls from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in('r','p') and n.nspname in('sellerpilot_private','storage','auth','vault')`;
const policySql=`select schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check from pg_policies where schemaname in('sellerpilot_private','storage','auth','vault')`;
const sorted=rows=>rows.map(r=>JSON.stringify(r)).sort();const diff=(a,b)=>b.filter(x=>!new Set(sorted(a)).has(JSON.stringify(x)));
const agg=sql=>`select coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb) from (${sql})x`;
const json=v=>q(JSON.stringify(v))+'::jsonb';
const check=(condition,error)=>`if not (${condition}) then raise exception ${q(error)};end if;`;
const exactRows=(sql,rows)=>`(${agg(sql)})=(select coalesce(jsonb_agg(x order by x::text),'[]'::jsonb)from jsonb_array_elements(${json(rows)})x)`;
const catalogGuard=(expected,label)=>check(`not exists(select 1 from jsonb_each(${json(expected)})e left join (${fnSql})f on f.signature=e.key where f.item is distinct from e.value)`,label);
const beforeAliases=new Set(aliases.map(([s])=>s.replaceAll(',',', ')));
const {db}=await realFixture({external:false});const outputs=[];
try{
 for(const [i,entry]of frozen.files.entries()){
  const file=entry.file,step=file.slice(9,12),version=file.slice(0,14),name=file.slice(15,-4),sourceBytes=await readFile(new URL('../supabase/migrations/'+file,import.meta.url)),source=sourceBytes.toString('utf8'),marker='$reviewed_external_'+step+'_source$';
  if(sha(sourceBytes)!==entry.sha256||!Buffer.from(source).equals(sourceBytes)||source.includes(marker)||(source.match(/^begin;$/gm)||[]).length!==1||(source.match(/^commit;\s*$/gm)||[]).length!==1)throw Error('FROZEN_SOURCE_OR_TRANSACTION_SHAPE');
  const stageTables=[...tables,...(i?['sellerpilot_private.external_detail_imports','sellerpilot_private.external_detail_import_audit']:[])];
  const digests=stageTables.map(t=>`select ${q(t)}::text kind,count(*)::bigint n,encode(sha256(convert_to(coalesce(string_agg(encode(sha256(convert_to((${t==='sellerpilot_private.products'&&i===0?"to_jsonb(r)-'external_detail_import_id'":'to_jsonb(r)'})::text,'UTF8')),'hex'),',' order by encode(sha256(convert_to((${t==='sellerpilot_private.products'&&i===0?"to_jsonb(r)-'external_detail_import_id'":'to_jsonb(r)'})::text,'UTF8')),'hex')),''),'UTF8')),'hex') digest from ${t} r${t==='storage.buckets'&&i===0?" where id<>'sellerpilot-detail-imports'":''}`).join('\nunion all\n');
  const preFunctions=(await db.query(fnSql)).rows,preTriggers=(await db.query(triggerSql)).rows,preConstraints=(await db.query(constraintsSql)).rows,preSecurity=(await db.query(securitySql)).rows;
  const deps=Object.fromEntries(preFunctions.filter(f=>Object.keys(live.functions).includes(f.signature)||frozen.functions.slice(0,i===0?0:i===1?1:3).some(x=>x.signature.replaceAll(',',', ')===f.signature)).map(f=>[f.signature,f.item]));
  for(const [sig,e]of Object.entries(live.functions)){const actual=deps[sig];if(!actual||actual.bodySha256!==e.bodySha256||actual.owner!==e.owner)throw Error('LIVE_DEPENDENCY_PIN_MISMATCH '+sig);const roles=actual.acl.map(a=>[a[0],a[2],a[3]]).sort();if(JSON.stringify(roles)!==JSON.stringify(e.acl.map(a=>[a.grantee,a.privilege,a.grantable]).sort()))throw Error('LIVE_DEPENDENCY_ACL_MISMATCH '+sig);}
  await db.exec(source);
  const postFunctions=(await db.query(fnSql)).rows,postTriggers=(await db.query(triggerSql)).rows,postConstraints=(await db.query(constraintsSql)).rows,postSecurity=(await db.query(securitySql)).rows;
  const sourceSigs=frozen.functions.filter(f=>f.migration===file).map(f=>f.signature.replaceAll(',',', '));
  const postExpected=Object.fromEntries(postFunctions.filter(f=>sourceSigs.includes(f.signature)||(i===2&&aliases.some(([,a])=>a.replaceAll(',',', ')===f.signature))).map(f=>[f.signature,f.item]));
  for(const f of frozen.functions.filter(f=>f.migration===file)){if(postExpected[f.signature.replaceAll(',',', ')].bodySha256!==f.bodySha256)throw Error('LOCAL_NEW_BODY_NOT_FROZEN');}
  const newTriggers=diff(preTriggers,postTriggers),newConstraints=diff(preConstraints,postConstraints),newSecurity=diff(preSecurity,postSecurity);
  const absentNames=sourceSigs.filter(s=>!(i===2&&beforeAliases.has(s))).concat(i===2?aliases.map(([,a])=>a):[]).map(s=>s.slice(0,s.indexOf('(')));
  const pristine=i===0?check(`to_regclass('sellerpilot_private.external_detail_imports') is null and to_regclass('sellerpilot_private.external_detail_import_audit') is null and not exists(select 1 from pg_attribute where attrelid='sellerpilot_private.products'::regclass and attname='external_detail_import_id' and not attisdropped) and not exists(select 1 from storage.buckets where id='sellerpilot-detail-imports')`,'EXTERNAL_NEW_OBJECT_COLLISION'):'';
  const absent=check(`not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname||'.'||p.proname=any(array[${absentNames.map(q).join(',')}]::text[]))`,'EXTERNAL_FUNCTION_COLLISION');
  const aliasesSql=i===2?aliases.map(([a,b])=>`select ${q(a)} before_sig,${q(b)} after_sig`).join(' union all '):`select null::text before_sig,null::text after_sig where false`;
  const requires=['20260905140000','20260905141000','20260905142000','20260906010000','20260906011000','20260906030000','20260906050000','20260906060000',...frozen.files.slice(0,i).map(f=>f.file.slice(0,14))];
  const historyCheck=check(`(select count(*) from supabase_migrations.schema_migrations)=${279+i} and not exists(select 1 from supabase_migrations.schema_migrations where version=${q(version)}) and not exists(select v from unnest(array[${requires.map(q).join(',')}])v where not exists(select 1 from supabase_migrations.schema_migrations h where h.version=v))`,'EXTERNAL_HISTORY_PREIMAGE');
  const before=`begin;\nset local lock_timeout='5s';set local statement_timeout='30s';\nlock table supabase_migrations.schema_migrations in share row exclusive mode;\ndo $external_pre$ begin
${check("current_user='postgres' and session_user='postgres'",'EXTERNAL_POSTGRES_SESSION_REQUIRED')}
${check('pg_try_advisory_xact_lock(193674997,20260905)','EXTERNAL_MIGRATION_BUSY')}
${historyCheck}
${check(`encode(sha256(convert_to(${marker}${source}${marker},'UTF8')),'hex')=${q(entry.sha256)}`,'EXTERNAL_SOURCE_SHA_MISMATCH')}
${pristine}${absent}${catalogGuard(deps,'EXTERNAL_DEPENDENCY_BODY_ACL_ABI_CHANGED')}
end $external_pre$;
lock table ${stageTables.join(',')} in share mode;
create temporary table reviewed_ext_history on commit drop as select version,md5(to_jsonb(h)::text) digest from supabase_migrations.schema_migrations h;
create temporary table reviewed_ext_rows on commit drop as ${digests};
create temporary table reviewed_ext_aliases on commit drop as select p.oid,a.after_sig,md5((to_jsonb(p)-array['proname','proacl'])::text) digest from (${aliasesSql})a join pg_proc p on p.oid=to_regprocedure(a.before_sig);
create temporary table reviewed_ext_functions on commit drop as select p.oid,md5(to_jsonb(p)::text) digest from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','sellerpilot_private') and not exists(select 1 from reviewed_ext_aliases a where a.oid=p.oid);
create temporary table reviewed_ext_triggers on commit drop as select t.oid,md5(to_jsonb(t)::text) digest from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('sellerpilot_private','storage','auth','vault');
create temporary table reviewed_ext_constraints on commit drop as ${constraintsSql};
create temporary table reviewed_ext_security on commit drop as ${securitySql};
create temporary table reviewed_ext_policies on commit drop as ${policySql};
`;
  const storage=check(`exists(select 1 from storage.buckets where id='sellerpilot-detail-imports' and name=id and public=false and file_size_limit=10485760 and allowed_mime_types=array['image/png']) and not exists(select 1 from sellerpilot_private.external_detail_imports) and not exists(select 1 from sellerpilot_private.external_detail_import_audit) and not exists(select 1 from sellerpilot_private.products where external_detail_import_id is not null)`,'EXTERNAL_BUCKET_OR_PRISTINE_IMPORT_POSTCONDITION');
  const newTriggerQuery=`${triggerSql} and not exists(select 1 from reviewed_ext_triggers b where b.oid=t.oid)`;
  const triggerPersistent=check(`not exists(select 1 from jsonb_array_elements(${json(newTriggers)})e where not exists(select 1 from (${triggerSql})t where to_jsonb(t)=e))`,'EXTERNAL_NEW_TRIGGER_POSTCONDITION');
  const persistentGuards=triggerPersistent+catalogGuard(postExpected,'EXTERNAL_FUNCTION_POSTCONDITION')+storage+check(`exists(select 1 from pg_attribute where attrelid='sellerpilot_private.products'::regclass and attname='external_detail_import_id' and atttypid='uuid'::regtype and not attnotnull) and exists(select 1 from pg_constraint where conrelid='sellerpilot_private.products'::regclass and confrelid='sellerpilot_private.external_detail_imports'::regclass and contype='f' and convalidated)`,'EXTERNAL_POINTER_FK_POSTCONDITION')+check(`(select count(*) from pg_class where oid in('sellerpilot_private.external_detail_imports'::regclass,'sellerpilot_private.external_detail_import_audit'::regclass) and relrowsecurity and not relforcerowsecurity and relowner='postgres'::regrole)=2 and not exists(select 1 from pg_policies where schemaname='sellerpilot_private' and tablename in('external_detail_imports','external_detail_import_audit')) and not exists(select 1 from pg_class c,aclexplode(coalesce(c.relacl,acldefault('r',c.relowner)))a where c.oid in('sellerpilot_private.external_detail_imports'::regclass,'sellerpilot_private.external_detail_import_audit'::regclass) and (a.grantee<>c.relowner or a.is_grantable))`,'EXTERNAL_TABLE_SECURITY_POSTCONDITION');
  const postChecks=`${persistentGuards}
${check(`not exists(select 1 from reviewed_ext_history b left join supabase_migrations.schema_migrations h using(version) where h.version is null or md5(to_jsonb(h)::text) is distinct from b.digest)`,'EXTERNAL_EXISTING_HISTORY_CHANGED')}
${check(`not exists(select 1 from reviewed_ext_aliases a left join pg_proc p on p.oid=a.oid where p.oid is null or p.oid is distinct from to_regprocedure(a.after_sig) or md5((to_jsonb(p)-array['proname','proacl'])::text) is distinct from a.digest)`,'EXTERNAL_ALIAS_ORIGINAL_ABI_CHANGED')}
${check(`not exists(select 1 from reviewed_ext_functions b left join pg_proc p on p.oid=b.oid where p.oid is null or md5(to_jsonb(p)::text) is distinct from b.digest) and (select count(*) from (${fnSql})f)=(select count(*) from reviewed_ext_functions)+(select count(*) from reviewed_ext_aliases)+${sourceSigs.length}`,'EXTERNAL_UNEXPECTED_FUNCTION_CHANGE')}
${check(`not exists(select 1 from reviewed_ext_triggers b left join pg_trigger t on t.oid=b.oid where t.oid is null or md5(to_jsonb(t)::text) is distinct from b.digest) and ${exactRows(newTriggerQuery,newTriggers)}`,'EXTERNAL_UNEXPECTED_TRIGGER_CHANGE')}
${check(`not exists((select * from reviewed_ext_constraints) except (${constraintsSql})) and ${exactRows(`(${constraintsSql}) except (select * from reviewed_ext_constraints)`,newConstraints)}`,'EXTERNAL_CONSTRAINT_CHANGED')}
${check(`not exists((select * from reviewed_ext_security) except (${securitySql})) and ${exactRows(`(${securitySql}) except (select * from reviewed_ext_security)`,newSecurity)}`,'EXTERNAL_SECURITY_CHANGED')}
${check(`not exists((select * from reviewed_ext_policies) except (${policySql})) and not exists((${policySql}) except (select * from reviewed_ext_policies))`,'EXTERNAL_POLICY_CHANGED')}
${check(`not exists((select * from reviewed_ext_rows) except (${digests})) and not exists((${digests}) except (select * from reviewed_ext_rows))`,'EXTERNAL_EXISTING_BUSINESS_ROWS_CHANGED')}`;
  const historyPost=check(`(select count(*) from supabase_migrations.schema_migrations)=${280+i} and exists(select 1 from supabase_migrations.schema_migrations where version=${q(version)} and name=${q(name)} and cardinality(statements)=1 and statements[1]=${marker}${source}${marker} and encode(sha256(convert_to(statements[1],'UTF8')),'hex')=${q(entry.sha256)})`,'EXTERNAL_HISTORY_SOURCE_POSTCONDITION');
  const after=`do $external_post$ begin\n${postChecks}\nend $external_post$;\ninsert into supabase_migrations.schema_migrations(version,name,statements)values(${q(version)},${q(name)},array[${marker}${source}${marker}]);\ndo $external_history$ begin ${historyPost} end $external_history$;\ncommit;`;
  const sql=source.replace(/^(begin;|commit;\s*)$/gm,m=>m.trim()==='begin;'?before:after);
  const copies=sql.split(marker);if(copies.length!==7||[copies[1],copies[3],copies[5]].some(s=>!Buffer.from(s).equals(sourceBytes)))throw Error('EMBEDDED_SOURCE_NOT_BYTE_EXACT');
  const postread=`begin transaction isolation level repeatable read read only;set local lock_timeout='2s';set local statement_timeout='30s';\ndo $external_postread$ begin ${persistentGuards}${historyPost} end $external_postread$;\nselect jsonb_build_object('version',${q(version)},'historyCount',(select count(*) from supabase_migrations.schema_migrations),'sourceExact',exists(select 1 from supabase_migrations.schema_migrations where version=${q(version)} and statements=array[${marker}${source}${marker}]),'functions',(${agg(`${fnSql} and p.oid=any(array[${Object.keys(postExpected).map(s=>`to_regprocedure(${q(s)})`).join(',')}])`)}),'triggers',(${agg(triggerSql)}),'rowDigests',(${agg(digests)}),'bucket',(select to_jsonb(b)from storage.buckets b where id='sellerpilot-detail-imports')) as external_postcondition;\nrollback;`;
  const postCopies=postread.split(marker);if(postCopies.length!==5||[postCopies[1],postCopies[3]].some(s=>!Buffer.from(s).equals(sourceBytes)))throw Error('POSTREAD_EMBEDDED_SOURCE_NOT_EXACT');
  const manifest={status:'LOCAL_TEST_ONLY_NOT_OPERATING_APPROVAL',step,version,sourceFile:file,sourceSha256:entry.sha256,sourceBytes:sourceBytes.length,historyBefore:279+i,historyAfter:280+i,sqlSha256:sha(sql),postreadSha256:sha(postread),embeddedSourceCopies:3,postreadSourceCopies:2,functions:postExpected,dependencies:deps,newTriggers,newConstraints,newSecurity,guardedTables:stageTables,excludedBusinessColumns:i===0?{'sellerpilot_private.products':['external_detail_import_id']}: {},bucketAdditionExcludedFromExistingRows:i===0,operationalCalls:0,parentApprovalFlagWritten:false,existingPackage:{pre:125,post:97,unchanged:true},limitations:['Local PGlite expected ABI catalog, not operating postread','Fresh parent capture after 500/600 and pre125 mandatory before 400','Native concurrency, 30s cardinality performance and Vault encryption unverified','Postread cannot reconstruct dropped transaction pre-digests; wrapper enforces before/after equality atomically']};
  const prefix=tmp+'external'+step+'-reviewed';await writeFile(prefix+'-apply.sql',sql,{mode:0o600});await writeFile(prefix+'-postread.sql',postread,{mode:0o600});await writeFile(prefix+'-manifest.json',JSON.stringify(manifest,null,2)+'\n',{mode:0o600});outputs.push({step,prefix,historyBefore:279+i,historyAfter:280+i,sourceSha256:entry.sha256});
 }
 await writeFile(tmp+'external-reviewed-wrapper-index.json',JSON.stringify(outputs,null,2));return outputs;
}finally{await db.close();}

}
