import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{PGlite}from'@electric-sql/pglite';
const migration=await readFile(new URL('../supabase/migrations/20260906040000_external_detail_import.sql',import.meta.url),'utf8');
const owner='11111111-1111-4111-8111-111111111111',product='1ed4acfc-7603-48ec-a638-241131e59358',id='22222222-2222-4222-8222-222222222222',job='33333333-3333-4333-8333-333333333333',time='2026-09-05T12:00:00.123456+00:00',hash='a'.repeat(64);
const assets=Array.from({length:8},(_,i)=>({assetId:String(i),role:'role'+i,sourceSha256:String(i).repeat(64),byteLength:100}));
const receipts=assets.map((a,i)=>({...a,decodedRgbaSha256:String(i).repeat(64),verification:'bytes_only_not_approved'}));
const payload={importId:id,productId:product,ownerId:owner,actorId:owner,expectedProductUpdatedAt:time,expectedDetailVersion:1,expectedAiJobId:job,requestSha256:hash,source:{kind:'external_generated'},assets,originalEvidence:[{path:'original',sha256:hash}],reviewedCopy:Object.fromEntries(['ko','ja','en'].map(l=>[l,{document:{root:{},content:[]},documentSha256:hash,reviewNote:'reviewed '+l}]))};
export async function fixture(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create schema sellerpilot_private;
create table auth.users(id uuid primary key);create table sellerpilot_private.admin_users(user_id uuid primary key);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table sellerpilot_private.ai_cli_jobs(id uuid primary key,status text,request_payload jsonb,result_payload jsonb);
create table sellerpilot_private.products(id uuid primary key,owner_id uuid,demo boolean,status text,updated_at timestamptz,detail_page_version bigint,ai_job_id uuid,detail_page_data jsonb,detail_page_approved_version bigint,detail_page_image_manifest jsonb,detail_page_updated_at timestamptz);
insert into auth.users values('${owner}');insert into sellerpilot_private.admin_users values('${owner}');insert into sellerpilot_private.ai_cli_jobs values('${job}','failed','{"image_paths":["${owner}/original.png"]}','{"degraded":true}');
insert into sellerpilot_private.products values('${product}','${owner}',false,'draft','${time}',1,'${job}','{}',0,null,null);`);await db.exec(migration);await db.exec('create table sellerpilot_private.channel_gateway_jobs(id uuid primary key default gen_random_uuid(),created_by uuid,channel text,operation text,status text,provider_mutation_started_at timestamptz,request_payload jsonb)');await db.exec(await readFile(new URL('../supabase/migrations/20260906043000_external_detail_channel_fence.sql',import.meta.url),'utf8'));return db;}
async function call(db,action,body={},actor=owner,target=product){return (await db.query('select public.sellerpilot_service_external_detail_import($1,$2,$3,$4,$5::jsonb) as value',[action,actor,target,id,JSON.stringify(body)])).rows[0].value;}
const proof={requestSha256:hash,receipts,reviewConfirmed:true};
test('reserve/verify/atomic approval; idempotent replay; never changes failed AI lineage',async()=>{const db=await fixture();try{const before=(await db.query('select * from sellerpilot_private.ai_cli_jobs')).rows;assert.equal((await call(db,'context')).productUpdatedAt,time);assert.equal((await call(db,'reserve',payload)).status,'reserved');assert.equal((await call(db,'reserve',payload)).status,'reserved');await assert.rejects(call(db,'approve',proof),/VERIFICATION_REQUIRED/);assert.equal((await call(db,'verify',proof)).status,'verified');assert.equal((await call(db,'approve',proof)).status,'approved');assert.equal((await call(db,'approve',proof)).status,'approved');assert.equal((await call(db,'get')).current,true);assert.deepEqual((await db.query('select * from sellerpilot_private.ai_cli_jobs')).rows,before);assert.equal((await db.query('select detail_page_version from sellerpilot_private.products')).rows[0].detail_page_version,2);}finally{await db.close();}});
test('ownership, fixed target, request collision and microsecond fences fail closed',async()=>{const db=await fixture();try{await assert.rejects(call(db,'context',{},id),/OWNER_REQUIRED/);await assert.rejects(call(db,'context',{},owner,job),/TARGET_FORBIDDEN/);await assert.rejects(call(db,'reserve',{...payload,expectedProductUpdatedAt:'2026-09-05T12:00:00.123457+00:00'}),/VERSION_CONFLICT/);await call(db,'reserve',payload);await assert.rejects(call(db,'reserve',{...payload,requestSha256:'b'.repeat(64)}),/IDEMPOTENCY_CONFLICT/);await db.exec("update sellerpilot_private.products set updated_at=updated_at+interval '1 microsecond'");await assert.rejects(call(db,'verify',proof),/VERSION_CONFLICT/);}finally{await db.close();}});
test('partial uploads, duplicated pixels, absent copy, cancellation and expiry cannot approve',async()=>{const db=await fixture();try{await assert.rejects(call(db,'reserve',{...payload,reviewedCopy:{ko:payload.reviewedCopy.ko}}),/COPY_REQUIRED/);await call(db,'reserve',payload);await assert.rejects(call(db,'verify',{...proof,receipts:receipts.slice(0,7)}),/VERIFICATION_REQUIRED/);await assert.rejects(call(db,'verify',{...proof,receipts:receipts.map(r=>({...r,decodedRgbaSha256:hash}))}),/PIXELS_DUPLICATED/);await call(db,'cancel');await assert.rejects(call(db,'verify',proof),/STATE_CONFLICT/);assert.equal((await call(db,'cancel')).status,'cancelled');}finally{await db.close();}});
test('approval invalidates after product change, expired draft stays private',async()=>{const db=await fixture();try{await call(db,'reserve',payload);await db.exec("update sellerpilot_private.external_detail_imports set expires_at=now()-interval '1 second'");await assert.rejects(call(db,'verify',proof),/STATE_CONFLICT/);await db.exec("update sellerpilot_private.external_detail_imports set expires_at=now()+interval '1 day'");await call(db,'verify',proof);await call(db,'approve',proof);await db.exec("update sellerpilot_private.products set updated_at=updated_at+interval '1 microsecond'");assert.equal((await call(db,'get')).current,false);await assert.rejects(call(db,'approve',proof),/VERSION_CONFLICT/);}finally{await db.close();}});
test('RPC is service-only, tables private, bucket not public',async()=>{const db=await fixture();try{for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'public.sellerpilot_service_external_detail_import(text,uuid,uuid,uuid,jsonb)','EXECUTE') as v",[role])).rows[0].v,false);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("select has_table_privilege($1,'sellerpilot_private.external_detail_imports','SELECT') as v",[role])).rows[0].v,false);assert.equal((await db.query('select public from storage.buckets')).rows[0].public,false);}finally{await db.close();}});

test('external enqueue image/locale/version fence and in-flight product guard',async()=>{const db=await fixture();try{await call(db,'reserve',payload);await call(db,'verify',proof);const approved=await call(db,'approve',proof);const binding={productId:product,importId:id,ownerId:owner,requestSha256:hash,productUpdatedAt:approved.approved_product_updated_at,version:2,channel:'qoo10',market:'JP',language:'ja',locale:'ja-JP',documentSha256:hash,imageSha256s:assets.map(a=>a.sourceSha256),pixelSha256s:receipts.map(r=>r.decodedRgbaSha256)};const enqueue=b=>db.query("insert into sellerpilot_private.channel_gateway_jobs(created_by,channel,operation,status,request_payload) values($1,'qoo10','listing.update','queued',$2::jsonb)",[owner,JSON.stringify({arguments:{sellerpilotExternalDetail:b,publicationExpectedLocale:'ja-JP'}})]);await assert.rejects(enqueue({...binding,locale:'en-US'}),/LOCALE_INVALID/);await assert.rejects(enqueue({...binding,version:1}),/SOURCE_STALE/);await enqueue(binding);await assert.rejects(db.exec("update sellerpilot_private.products set detail_page_version=3"),/INFLIGHT_PUBLICATION/);await db.exec("update sellerpilot_private.channel_gateway_jobs set status='succeeded'");await db.exec("update sellerpilot_private.products set detail_page_version=3");}finally{await db.close();}});
