import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import test from "node:test";
const source=await readFile(new URL("../scripts/live-channel-operation.mjs",import.meta.url),"utf8");
const stripped=source.replace(/^import .*;\n/gm,"").replace("export async function authorizeLiveChannelOwner","async function authorizeLiveChannelOwner");
const owner="11111111-1111-4111-8111-111111111111",foreign="33333333-3333-4333-8333-333333333333";
const credential={id:"22222222-2222-4222-8222-222222222222",channel:"coupang",environment:"production",status:"active",version:7,expires_at:null};
// The acting administrator is intentionally NOT the credential's original creator.
const validProof={contractVersion:1,authorizationModel:"shared_admin_workspace",actorId:owner,credentialId:credential.id,credentialOwnerId:foreign,channel:credential.channel,environment:credential.environment,credentialVersion:7,expiresAt:null};
const marker="PRIVATE_VALUE_MUST_NOT_APPEAR";
const base={LIVE_ADMIN_ACCESS_TOKEN:marker,LIVE_ADMIN_USER_ID:owner,LIVE_CHANNEL:"coupang",LIVE_OPERATION:"diagnostic.test",LIVE_IDEMPOTENCY_KEY:"approved-existing-request-123",SUPABASE_KEYS_JSON:JSON.stringify([{type:"publishable",api_key:"fixture-public"},{type:"secret",api_key:"fixture-service"}])};
async function run({env={},rows=[credential],userId=owner,admin=true,sessionError=null,hang="",shortTimeout=false,serviceError=null,response={},providerError=null,secretPayload=null,directResponse=null,proofResponses=[{data:validProof,error:null}]}={}){
 const calls=[],requests=[],logs=[];let mutations=0,proofIndex=0;
 const process={env:{...base,...env},exitCode:0};
 const ctx=vm.createContext({URL,URLSearchParams,AbortController,AbortSignal,setTimeout,clearTimeout,process,
 console:{log:x=>logs.push(JSON.parse(x)),error:x=>logs.push(JSON.parse(x))},
 createClient(url,key,options){calls.push({kind:"client",url,key,options});if(key==="fixture-service")return{rpc:async()=>{calls.push({kind:"decrypt"});if(hang==="decrypt")return new Promise(()=>{});if(serviceError)return{error:serviceError};return{data:secretPayload??{access_token:marker,main_account_id:marker,shop_ids:[marker],shopee_targets:[]},error:null};}};
 return {auth:{admin:new Proxy({},{get(){return()=>{mutations++;throw Error("auth mutation");};}}),getUser:async()=>{calls.push({kind:"getUser"});if(hang==="getUser")return new Promise(()=>{});return{data:{user:{id:userId}},error:sessionError};}},rpc:async (name,args)=>{calls.push({kind:name,args});if(hang===name)return new Promise(()=>{});if(name==="sellerpilot_verify_channel_credential_owner_v1")return proofResponses[Math.min(proofIndex++,proofResponses.length-1)];return{data:name==="sellerpilot_is_admin"?admin:rows,error:null};}};},
 fetch:async(url,init={})=>{requests.push({url:String(url),...init});if(providerError)throw providerError;return{ok:true,status:200,json:async()=>response};},
 shopeeRequest:async()=>{calls.push({kind:"provider"});if(directResponse)return directResponse;throw new Error(marker);},shopeeMerchantRequest:async()=>{calls.push({kind:"provider"});if(directResponse)return directResponse;throw new Error(marker);}});
 let code=stripped;
 if(shortTimeout)code=code.replace('timeoutMs = 30_000','timeoutMs = 15').replace('Date.now() + 30_000','Date.now() + 15');
 await vm.runInContext(`(async()=>{${code}\n})()`,ctx,{timeout:1000});
 return {calls,requests,logs,mutations,exitCode:process.exitCode};
}
const lastCode=r=>r.logs.at(-1)?.code;
test("no account mutation, generated sign-in, sample pricing/SKU or random idempotency remains",()=>{
 assert.doesNotMatch(source,/auth\.admin|signInWithPassword|updateUserById|createUser|generateLink|email_confirm|sampleUser|sampleEmail|randomBytes|createHash|original_price: 12\.9|weight: 0\.35|GLOBAL-\$\{/);
});
test("no token: entire CLI has zero clients, DB, provider or app requests",async()=>{const r=await run({env:{LIVE_ADMIN_ACCESS_TOKEN:""}});assert.equal(lastCode(r),"LIVE_ADMIN_ACCESS_TOKEN_REQUIRED");assert.equal(r.calls.length,0);assert.equal(r.requests.length,0);assert.equal(r.mutations,0);});
for(const value of ["http://untrusted.invalid","https://untrusted.invalid","http://sellerpilot-global.vercel.app","https://sellerpilot-global-preview.vercel.app","https://sellerpilot-global.vercel.app@untrusted.invalid","https://sellerpilot-global.vercel.app/path","https://sellerpilot-global.vercel.app?token=x"]){test(`unapproved destination fails before any network: ${value}`,async()=>{const r=await run({env:{SELLERPILOT_URL:value}});assert.equal(lastCode(r),"LIVE_UNAPPROVED_ORIGIN");assert.equal(r.calls.length+r.requests.length,0);});}
test("foreign Supabase project fails before sending Bearer",async()=>{const r=await run({env:{SUPABASE_PROJECT_REF:"foreignproject"}});assert.equal(lastCode(r),"LIVE_UNAPPROVED_PROJECT");assert.equal(r.calls.length+r.requests.length,0);});
test("server list contract omits credential owner; gateway uses private created_by",async()=>{
 const sql=await readFile(new URL("../supabase/migrations/20260816060000_channel_credentials_and_roles.sql",import.meta.url),"utf8");
 const contract=sql.slice(sql.indexOf("create or replace function public.sellerpilot_list_credentials()"));
 assert.doesNotMatch(contract.slice(0,contract.indexOf("language plpgsql")),/created_by|owner_id|user_id/);
 const claim=await readFile(new URL("../supabase/migrations/20260825111820_serialize_gateway_ledger_transactions.sql",import.meta.url),"utf8");assert.match(claim,/credential\.environment, credential\.created_by/);
});
for(const proof of [{},{created_by:owner,owner_id:owner},{created_by:foreign,owner_id:foreign,ownerId:foreign,user_id:foreign}]){test(`no guessed owner proof can authorize privileged access: ${JSON.stringify(proof)}`,async()=>{const r=await run({rows:[{...credential,...proof}],proofResponses:[{data:null,error:{code:"PGRST202",message:marker}}]});assert.equal(lastCode(r),"LIVE_CREDENTIAL_OWNER_PROOF_UNAVAILABLE");assert.equal(r.calls.filter(x=>x.kind==="client").length,1);assert.equal(r.requests.length,0);assert.equal(r.mutations,0);});}
test("wrong or unapproved administrator cannot reach credentials",async()=>{for(const c of [{userId:foreign},{admin:false},{sessionError:{message:marker}}]){const r=await run(c);assert.equal(r.calls.some(x=>x.kind==="sellerpilot_list_credentials"),false);assert.equal(r.requests.length,0);assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));}});
for(const stage of ["getUser","sellerpilot_is_admin","sellerpilot_list_credentials","sellerpilot_verify_channel_credential_owner_v1"]){test(`whole CLI timeout boundary at ${stage}`,async()=>{const start=Date.now();const r=await run({hang:stage,shortTimeout:true});assert.equal(lastCode(r),"LIVE_ADMIN_VERIFICATION_TIMEOUT");assert.ok(Date.now()-start<1000);assert.equal(r.requests.length,0);});}
test("verification timeout cannot exceed 30s",()=>{assert.match(source,/Math\.min\(30_000, timeoutMs\)/);assert.match(source,/AbortSignal\.any\(\[controller\.signal, init\.signal\]\)/);});
test("malformed arguments or secret-key JSON cannot escape raw input",async()=>{for(const key of ["LIVE_OPERATION_ARGUMENTS","SUPABASE_KEYS_JSON"]){const r=await run({env:{[key]:`{"secret":"${marker}",bad}`}});assert.equal(r.exitCode,1);assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));assert.equal(r.requests.length+r.calls.length,0);}});
test("privileged RPC error has fixed top-level boundary (real authorization flow with mocked RPCs)",async()=>{const r=await run({env:{LIVE_CREDENTIAL_DIAGNOSTICS:"true"},serviceError:{message:marker,details:marker}});assert.equal(lastCode(r),"LIVE_CHANNEL_OPERATION_FAILED");assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));});
for(const mode of [{},{LIVE_LAZADA_START_OAUTH:"true"},{LIVE_SHOPEE_START_OAUTH:"true"},{LIVE_TARGET_DIAGNOSTICS:"true"}]){test(`raw API/OAuth payload and aliases never leave stdout: ${JSON.stringify(mode)}`,async()=>{const r=await run({env:mode,response:{access_token:marker,client_secret:marker,status:marker,httpStatus:marker,message:marker,authorizationUrl:marker,id:marker,remoteId:marker,providerBody:{value:marker}}});assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));for(const log of r.logs)assert.deepEqual(Object.keys(log).sort(),["httpStatus","ok"]);assert.ok(r.requests.every(q=>q.redirect==="error"&&q.url.startsWith("https://sellerpilot-global.vercel.app/")));});}
test("provider exceptions and credential diagnostic aliases remain redacted",async()=>{for(const config of [{providerError:{message:marker}},{env:{LIVE_CREDENTIAL_DIAGNOSTICS:"true"}}]){const r=await run({...config});assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));}});
test("production test-product mode refuses before auth even with write approval",async()=>{const r=await run({env:{LIVE_CHANNEL:"shopee",LIVE_OPERATION:"listing.create",LIVE_SHOPEE_GLOBAL_TEST_PRODUCT_ID:"fixture-product",LIVE_CONFIRM_WRITE:"true"}});assert.equal(lastCode(r),"LIVE_DISABLED_TEST_MODE");assert.equal(r.requests.length+r.calls.length,0);});
test("general operation requires explicit stable idempotency and central resource IDs",async()=>{for(const env of [{LIVE_IDEMPOTENCY_KEY:""},{LIVE_OPERATION:"listing.create"},{LIVE_OPERATION:"listing.update",LIVE_PRODUCT_ID:owner},{LIVE_OPERATION:"shipment.confirm"}]){const r=await run({env});assert.match(lastCode(r),/LIVE_(IDEMPOTENCY_KEY_REQUIRED|RESOURCE_ID_REQUIRED)/);assert.equal(r.requests.length+r.calls.length,0);}});
test("existing IDs/idempotency passed unchanged, never fabricated (real authorization flow with mocked RPCs)",async()=>{const r=await run({env:{LIVE_OPERATION:"listing.update",LIVE_PRODUCT_ID:owner,LIVE_RESOURCE_LISTING_ID:credential.id,LIVE_CONFIRM_WRITE:"true"}});const req=JSON.parse(r.requests[0].body);assert.equal(req.idempotencyKey,base.LIVE_IDEMPOTENCY_KEY);assert.equal(req.productId,owner);assert.equal(req.resourceListingId,credential.id);assert.deepEqual(req.arguments,{});});

test("credential ambiguity and invalid environment fail closed",async()=>{for(const config of [{rows:[credential,credential]},{rows:[]},{rows:[{...credential,status:"revoked"}]},{env:{LIVE_ENVIRONMENT:"other"}}]){const r=await run(config);assert.match(lastCode(r),/LIVE_(ACTIVE_CREDENTIAL_NOT_UNIQUE|ENVIRONMENT_INVALID)/);assert.equal(r.requests.length,0);assert.equal(r.calls.filter(x=>x.kind==="client").length,1);}});
test("direct provider GET errors and raw aliased data never escape (real authorization flow with mocked RPCs)",async()=>{const secretPayload={access_token:marker,shop_id:"existing-shop",access_token_expires_at:"2099-01-01T00:00:00Z"};for(const directResponse of [null,{response:{status:200},data:{seller_id:marker,token_alias:marker,secret:marker}}]){const r=await run({env:{LIVE_SHOPEE_ITEM_ID:"existing-item",LIVE_TARGET_ID:"existing-shop"},secretPayload,directResponse});assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));if(!directResponse)assert.equal(lastCode(r),"LIVE_CHANNEL_OPERATION_FAILED");}});
test("Shopee direct GET never substitutes sample shop or merchant target",async()=>{const r=await run({env:{LIVE_SHOPEE_ITEM_ID:"existing-item"}});assert.equal(lastCode(r),"LIVE_EXPLICIT_SHOPEE_TARGET_REQUIRED");assert.equal(r.requests.length,0);});

test("shared administrator authorizes only after exact actor/metadata checks while preserving distinct credential owner",async()=>{const r=await run();assert.equal(r.exitCode,0);assert.equal(r.requests.length,1);const proofCall=r.calls.find(x=>x.kind==="sellerpilot_verify_channel_credential_owner_v1");assert.deepEqual(JSON.parse(JSON.stringify(proofCall.args)),{p_credential_id:credential.id,p_channel:"coupang",p_environment:"production"});assert.ok(r.calls.findIndex(x=>x.kind==="sellerpilot_verify_channel_credential_owner_v1")<r.calls.findIndex(x=>x.key==="fixture-service"));assert.equal(r.mutations,0);});
for(const bad of [null,[],{}, {...validProof,contractVersion:"1"},{...validProof,contractVersion:2},{...validProof,credentialId:foreign},{...validProof,ownerId:foreign},{...validProof,actorId:foreign},{...validProof,actorId:null},{...validProof,credentialOwnerId:null},{...validProof,credentialOwnerId:"not-a-uuid"},{...validProof,authorizationModel:"exclusive_owner"},{...validProof,channel:"shopee"},{...validProof,environment:"sandbox"},{...validProof,credentialVersion:8},{...validProof,credentialVersion:"7"},{...validProof,expiresAt:"2000-01-01T00:00:00Z"},{...validProof,expiresAt:"invalid"},{...validProof,secret:marker}]){test(`invalid proof blocks all privileged/downstream calls: ${JSON.stringify(bad)}`,async()=>{const r=await run({proofResponses:[{data:bad,error:null}]});assert.equal(lastCode(r),"LIVE_CREDENTIAL_OWNER_PROOF_INVALID");assert.equal(r.requests.length,0);assert.equal(r.calls.filter(x=>x.kind==="client").length,1);assert.equal(r.calls.some(x=>["decrypt","provider"].includes(x.kind)),false);assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));});}
test("RPC absent, denied or returned error cannot fall back to metadata owner aliases",async()=>{for(const code of ["PGRST202","42883","42501"]){const r=await run({rows:[{...credential,owner_id:owner,created_by:owner}],proofResponses:[{data:validProof,error:{code,message:marker}}]});assert.equal(lastCode(r),"LIVE_CREDENTIAL_OWNER_PROOF_UNAVAILABLE");assert.equal(r.requests.length,0);assert.equal(r.calls.filter(x=>x.kind==="client").length,1);}});
test("decrypt is followed by authenticated proof before provider use; rotation/revocation fails closed",async()=>{for(const second of [{data:{...validProof,credentialVersion:8},error:null},{data:null,error:{code:"42501"}},{data:{...validProof,credentialOwnerId:owner},error:null},{data:{...validProof,actorId:foreign},error:null},{data:{...validProof,expiresAt:"2000-01-01"},error:null}]){const r=await run({env:{LIVE_SHOPEE_ITEM_ID:"existing-item",LIVE_TARGET_ID:"existing-shop"},proofResponses:[{data:validProof,error:null},second]});assert.equal(r.calls.filter(x=>x.kind==="decrypt").length,1);assert.equal(r.calls.filter(x=>x.kind==="sellerpilot_verify_channel_credential_owner_v1").length,2);assert.equal(r.calls.some(x=>x.kind==="provider"),false);assert.equal(r.requests.length,0);assert.match(lastCode(r),/LIVE_CREDENTIAL_OWNER_PROOF_(INVALID|UNAVAILABLE|CHANGED)/);}});
test("unchanged proof after decrypt allows mocked existing-item GET only",async()=>{const r=await run({env:{LIVE_SHOPEE_ITEM_ID:"existing-item",LIVE_TARGET_ID:"existing-shop"},secretPayload:{access_token:marker,shop_id:"existing-shop",access_token_expires_at:"2099-01-01T00:00:00Z"},directResponse:{response:{status:200},data:{secret:marker}}});assert.equal(r.exitCode,0);const kinds=r.calls.map(x=>x.kind);assert.equal(kinds.filter(x=>x==="sellerpilot_verify_channel_credential_owner_v1").length,2);assert.ok(kinds.indexOf("decrypt")<kinds.lastIndexOf("sellerpilot_verify_channel_credential_owner_v1"));assert.ok(kinds.lastIndexOf("sellerpilot_verify_channel_credential_owner_v1")<kinds.indexOf("provider"));assert.doesNotMatch(JSON.stringify(r.logs),new RegExp(marker));});

test("decrypt timeout uses shared verification deadline and never reaches provider",async()=>{const r=await run({env:{LIVE_CREDENTIAL_DIAGNOSTICS:"true"},hang:"decrypt",shortTimeout:true});assert.equal(lastCode(r),"LIVE_ADMIN_VERIFICATION_TIMEOUT");assert.equal(r.calls.filter(x=>x.kind==="decrypt").length,1);assert.equal(r.requests.length,0);assert.equal(r.calls.some(x=>x.kind==="provider"),false);});

test("matching future expiry passes; metadata expiry mismatch and non-UUID identity deny",async()=>{const expiry="2099-01-01T00:00:00+00:00";const good=await run({rows:[{...credential,expires_at:expiry}],proofResponses:[{data:{...validProof,expiresAt:expiry},error:null}]});assert.equal(good.requests.length,1);const changed=await run({rows:[{...credential,expires_at:expiry}],proofResponses:[{data:validProof,error:null}]});assert.equal(lastCode(changed),"LIVE_CREDENTIAL_OWNER_PROOF_INVALID");assert.equal(changed.requests.length,0);const malformed=await run({rows:[{...credential,id:"not-a-uuid"}],proofResponses:[{data:{...validProof,credentialId:"not-a-uuid"},error:null}]});assert.equal(lastCode(malformed),"LIVE_CREDENTIAL_OWNER_PROOF_INVALID");assert.equal(malformed.requests.length,0);});


test("legacy owner equality proof is rejected rather than misread as shared access", async () => {
 const legacy={contractVersion:1,credentialId:credential.id,ownerId:owner,channel:credential.channel,environment:credential.environment,credentialVersion:7,expiresAt:null};
 const result=await run({proofResponses:[{data:legacy,error:null}]});
 assert.equal(lastCode(result),"LIVE_CREDENTIAL_OWNER_PROOF_INVALID");assert.equal(result.requests.length,0);
});
test("credential creator is not substituted into the actor Bearer or downstream resource payload", async () => {
 const result=await run();assert.equal(result.exitCode,0);
 const users=result.calls.filter(value=>value.kind==="client"&&value.key==="fixture-public");
 assert.ok(users.every(value=>value.options.global.headers.Authorization===`Bearer ${marker}`));
 assert.ok(result.requests.every(value=>value.headers.authorization===`Bearer ${marker}`));
 assert.ok(result.requests.every(value=>!String(value.body??"").includes(foreign)));
 assert.equal(result.mutations,0);
});
