import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the SellerPilot login experience", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<html lang="ko">/i);
  assert.match(html, /<title>SellerPilot \| 멀티채널 커머스 운영센터<\/title>/i);
  assert.match(html, /주문·상품·문의 업무를/);
  assert.match(html, /하나의 작업대에서/);
  assert.match(html, /운영센터 로그인/);
  assert.match(html, /Supabase Auth/);
  assert.match(html, /실데이터 전용/);
  assert.doesNotMatch(html, /demo@sellerpilot\.kr|seller2026|admin@company\.com|₩4,820,400|오늘의 운영 브리핑/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("contains the complete multi-channel operating storyboard and 175-item acceptance baseline", async () => {
  const [page, layout, styles, operationsStyles, packageJson, storyboard, channelConfig, channelLinks, acceptanceData, acceptancePage, exchangeRoute, readinessData, readinessPage, channelMapping, manifest, serviceWorker, pushManager, mobileStyles, revenueCalendar, adminAccessState] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/operations-system.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../docs/멀티채널_커머스_운영센터_스토리보드.md", import.meta.url), "utf8"),
    readFile(new URL("../app/channel-config.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/channel-links.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/acceptance-checklist-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/acceptance-checklist.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/api/exchange-rates/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/channel-readiness-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/channel-readiness.tsx", import.meta.url), "utf8"),
    readFile(new URL("../docs/판매채널_실계정_UI_필드_매핑.md", import.meta.url), "utf8"),
    readFile(new URL("../public/manifest.webmanifest", import.meta.url), "utf8"),
    readFile(new URL("../public/sw.js", import.meta.url), "utf8"),
    readFile(new URL("../app/mobile-push-manager.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/mobile-optimization.css", import.meta.url), "utf8"),
    readFile(new URL("../app/_dashboard/revenue-calendar.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/_auth/admin-access-state.ts", import.meta.url), "utf8"),
  ]);

  assert.match(page, /^"use client";/);
  assert.match(page, /통합 대시보드/);
  assert.match(page, /이번 달 판매 TOP 10/);
  assert.match(page, /기준 환율/);
  assert.match(page, /환율 새로고침/);
  assert.match(page, /const dashboardExchangeRateRefreshMs = 60_000/);
  assert.doesNotMatch(page, /Math\.random/);
  assert.doesNotMatch(page, /beforeunload|onbeforeunload/);
  assert.doesNotMatch(page, /sellerpilot-operation-sync-requested-at/);
  assert.doesNotMatch(page, /window\.setInterval\(run, 5 \* 60_000\)/);
  assert.equal((page.match(/window\.setInterval\(refreshWhenVisible, 10_000\)/g) ?? []).length, 1);
  assert.match(page, /const registrationActivityEntryRefreshRef = useRef\(false\)/);
  assert.match(page, /if \(view !== "registration-activity"\) \{\s*registrationActivityEntryRefreshRef\.current = false;\s*return;\s*\}\s*if \(registrationActivityEntryRefreshRef\.current\) return;\s*registrationActivityEntryRefreshRef\.current = true;\s*void refreshOperations\(\);/);
  assert.equal((page.match(/void refreshOperations\(\)/g) ?? []).length, 2);
  assert.match(page, /if \(view !== "registration-activity"\) return;[\s\S]{0,360}document\.visibilityState === "visible"[\s\S]{0,160}refreshOperations\(\)/);
  assert.match(page, /document\.addEventListener\("visibilitychange", refreshWhenVisible\)/);
  assert.match(page, /document\.removeEventListener\("visibilitychange", refreshWhenVisible\)/);
  assert.match(exchangeRoute, /api\.coinbase\.com\/v2\/exchange-rates\?currency=KRW/);
  assert.match(exchangeRoute, /api\.frankfurter\.dev\/v2\/rates/);
  assert.match(exchangeRoute, /minute-market/);
  assert.match(exchangeRoute, /daily-reference-fallback/);
  assert.match(exchangeRoute, /cache: "no-store"/);
  assert.match(exchangeRoute, /s-maxage=\$\{minuteMarketCdnSeconds\}/);
  assert.doesNotMatch(exchangeRoute, /stale-while-revalidate/);
  assert.match(page, /상품 관리/);
  assert.match(page, /상품 등록 센터/);
  assert.match(page, /마진 계산/);
  assert.match(page, /주문 · 판매/);
  assert.match(page, /CS 통합함/);
  assert.match(page, /Qoo10 Japan/);
  assert.match(page, /Shopee Global/);
  assert.match(page, /Lazada Malaysia/);
  assert.match(page, /쿠팡/);
  assert.match(page, /11번가/);
  assert.match(page, /Temu/);
  assert.match(page, /네이버 스마트스토어/);
  assert.match(page, /eBay Global/);
  assert.match(page, /서비스 스토리보드/);
  assert.match(page, /개발 · 실검수/);
  assert.match(page, /채널 연결 · 상태/);
  assert.ok(page.indexOf('label: "기획"') < page.indexOf('label: "스타일 학습 검증"'));
  assert.doesNotMatch(page, /id: "readiness"/);
  assert.doesNotMatch(page, /id: "credentials"/);
  assert.match(page, /commerce-service-rail/);
  assert.match(page, /통합 판매관리/);
  assert.match(page, /운영 키 확인 중/);
  assert.match(page, /읽기 진단 확인 중/);
  assert.match(page, /실상품 원장을 불러오는 중입니다/);
  assert.match(page, /운영 DB 확인이 끝날 때까지 0개로 확정하지 않습니다/);
  assert.match(page, /실상품 원장에 연결하지 못했습니다/);
  assert.match(page, /상품, 주문, 문의 검색/);
  assert.match(page, /value=\{searchQuery\}/);
  assert.match(page, /selectUnifiedSearchResult/);
  assert.match(page, /unifiedSearchResults\.products/);
  assert.match(page, /unifiedSearchResults\.orders/);
  assert.match(page, /unifiedSearchResults\.inquiries/);
  assert.match(page, /aria-label="주문 검색"/);
  assert.match(page, /aria-label="문의 검색"/);
  assert.doesNotMatch(page, /event\.key === "Escape" \|\| event\.key === "Enter"/);
  assert.match(page, /signInWithPassword/);
  assert.match(page, /Qoo10 Japan/);
  assert.match(page, /Shopee Global/);
  assert.match(page, /enabledSalesChannelCount\}개 판매채널/);
  assert.match(page, /summary\.activeCredentialCount\} \/ \$\{enabledSalesChannelCount\}/);
  assert.match(page, /실제 판매자센터 열기/);
  assert.match(channelLinks, /판매 상품 페이지 열기/);
  assert.doesNotMatch(channelLinks, /채널에서 상품 찾기/);
  assert.doesNotMatch(channelLinks, /#\/products\/origin-list/);
  assert.match(page, /publish-context/);
  assert.match(page, /if \(view === "product-detail"\) return activeSelectedProduct/);
  assert.match(page, /상품 상세정보를 불러오는 중입니다/);
  assert.match(page, /ChatGPT CLI가 문의 원문과 연결된 원장 정보가 있는지 확인/);
  assert.match(page, /공식 카테고리 확정/);
  assert.match(page, /대표사진 1장이 반드시 필요/);
  assert.match(page, /상품 링크 또는 설명/);
  assert.doesNotMatch(page, /상세정보 불러오기/);
  assert.match(page, /1차 정보·6장 생성/);
  assert.doesNotMatch(page, /공개 이미지 URL|URL로 불러오기/);
  assert.match(page, /id: "front"/);
  assert.match(page, /id: "barcode"/);
  assert.match(page, /option-photo-\$\{slot\.id\}/);
  assert.match(page, /id="extra-product-photos"[^>]*multiple/);
  assert.match(page, /id="main-product-photo-camera"[^>]*capture="environment"/);
  assert.match(page, /id=\{`option-photo-\$\{slot\.id\}-camera`\}[^>]*capture="environment"/);
  assert.match(page, /id="extra-product-photo-camera"[^>]*capture="environment"/);
  assert.match(page, /preservePublishingCaptureContext/);
  assert.match(page, /rememberWorkspaceView\("publishing"\)/);
  assert.match(page, /userWorkspaceStorageKey\(userId\)/);
  const aiProductStudio = await readFile(new URL("../app/ai-product-studio.tsx", import.meta.url), "utf8");
  const studioJobSession = await readFile(new URL("../app/_registration/studio-job-session.ts", import.meta.url), "utf8");
  const categoryWorkbench = await readFile(new URL("../app/category-classification-workbench.tsx", import.meta.url), "utf8");
  assert.match(studioJobSession, /sellerpilot:product-studio:active-job:v1/);
  assert.match(aiProductStudio, /activeStudioJobStorageKey/);
  assert.match(aiProductStudio, /이전 폼에서 시작한 상품 분석.*등록 이력에만 백그라운드 연결/);
  assert.doesNotMatch(aiProductStudio, /selectedRecoveryJobId|displayJobId\.current = selectedRecoveryJobId/);
  assert.match(aiProductStudio, /shouldDisplayStudioJob\(\{/);
  assert.match(aiProductStudio, /jobMonitors\.abortAll\(\)/);
  assert.match(aiProductStudio, /persistActiveStudioJob\(jobId, studioSessionId\)/);
  assert.match(aiProductStudio, /displayJobId\.current = "";[\s\S]*?displayJobId\.current = queued\.jobId/);
  assert.match(categoryWorkbench, /현재 검색어로 다시 추천/);
  assert.match(categoryWorkbench, /sellerpilot:category-workbench:/);
  assert.match(categoryWorkbench, /restoreCategoryStates\(productId\)/);
  assert.match(mobileStyles, /\.alert-list\s*\{\s*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\) !important/);
  assert.match(mobileStyles, /\.registration-card dl\s*\{[\s\S]*?display:\s*grid;[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.doesNotMatch(mobileStyles, /\.registration-card dl\s*\{\s*display:\s*none;/);
  assert.doesNotMatch(page, /<PublishingPage key=\{publishingProduct/);
  assert.match(page, /resolvedProductId = analyzedProductId \?\? initialProduct\?\.id \?\? null/);
  assert.match(page, /nextAdminAccessState\(current, event, Boolean\(session && session\.user\.id === verifiedAdminUserId\)\)/);
  assert.match(adminAccessState, /current === "admin" && sameVerifiedUser \? "admin" : "checking"/);
  assert.match(page, /const verificationState = adminVerificationState\(isAdmin, error\)/);
  assert.match(adminAccessState, /if \(rpcError\) return "error";[\s\S]*?if \(isAdmin === false\) return "forbidden"/);
  assert.match(page, /!active \|\| accountSwitchingRef\.current \|\| generation !== verificationGeneration/);
  assert.match(page, /latestSession\.session\.user\.id !== session\.user\.id/);
  assert.doesNotMatch(page, /setAccessState\(session \? "checking" : "signed_out"\)/);
  assert.match(page, /withPromiseTimeout\(Promise\.all\(\[/);
  assert.match(page, /12_000, "관리자 권한 확인 시간이 초과되었습니다\."/);
  assert.match(page, /12_000, "로그인 세션 확인 시간이 초과되었습니다\."/);
  assert.match(page, /setAccessState\("error"\)/);
  assert.match(page, /현재 세션 다시 확인/);
  assert.match(page, /<RevenueCalendar days=\{analytics\?\.daily \?\? \[\]\} range=\{salesRange\}/);
  assert.match(revenueCalendar, /domesticRevenueKrw/);
  assert.match(revenueCalendar, /overseasRevenueKrw/);
  assert.match(revenueCalendar, /국내 매출/);
  assert.match(revenueCalendar, /해외 매출/);
  assert.doesNotMatch(mobileStyles, /\.sales-calendar-grid small\s*\{\s*display:\s*none/);
  assert.doesNotMatch(mobileStyles, /\.channel-list \.channel-row \.channel-metric:nth-of-type/);
  assert.match(page, /channel-metric channel-revenue/);
  assert.match(page, /channel-metric channel-orders/);
  assert.match(page, /const params = new URLSearchParams\(\{ view: next \}\)/);
  assert.match(page, /if \(next === "registration-activity" && nextRegistrationStatus !== "all"\) \{[\s\S]{0,180}params\.set\("status", nextRegistrationStatus\)/);
  assert.match(page, /window\.history\.pushState\(historyState, "", `\$\{window\.location\.pathname\}\?\$\{params\.toString\(\)\}`\)/);
  assert.match(page, /사진 촬영/);
  assert.match(page, /앨범에서 선택/);
  assert.match(page, /상품 사실 설명/);
  assert.doesNotMatch(page, /자료 출처·상품 링크/);
  assert.match(page, /상세페이지 제작 시작/);
  assert.doesNotMatch(page, /대기열에 담기/);
  assert.doesNotMatch(page, /상품 동시 처리/);
  assert.doesNotMatch(page, /DEMO_DATA_META|createDemoStudioResult|seed_demo/);
  assert.match(page, /MarginCalculatorPage/);
  assert.match(styles, /\.margin-workspace/);
  const marginCalculator = await readFile(new URL("../app/margin-calculator.tsx", import.meta.url), "utf8");
  assert.match(marginCalculator, /8 CHANNEL COMPARISON/);
  assert.match(marginCalculator, /손익분기 판매가/);
  assert.match(marginCalculator, /목표 마진 권장 판매가/);
  assert.match(marginCalculator, /계산 결과 저장/);
  assert.match(marginCalculator, /자동 등록 가능/);
  assert.equal((marginCalculator.match(/key: "/g) ?? []).length, 8);
  assert.match(marginCalculator, /key: "elevenst"/);
  assert.match(channelConfig, /Shopee Global/);
  assert.match(channelConfig, /mark: "쿠팡"/);
  assert.match(channelConfig, /mark: "11번가"/);
  assert.match(channelConfig, /sellerCenterUrl/);
  assert.match(channelConfig, /Alibaba\.com/);
  assert.match(channelConfig, /1688\.com/);
  assert.doesNotMatch(channelConfig, /sales:|revenue:|customer:|샘플/);
  assert.match(layout, /og-style-learning\.png/);
  assert.match(manifest, /"display": "standalone"/);
  assert.match(manifest, /SellerPilot 판매관리/);
  assert.match(serviceWorker, /addEventListener\("push"/);
  assert.match(serviceWorker, /notificationclick/);
  assert.doesNotMatch(serviceWorker, /caches\.open|commerce_orders|customer/);
  assert.match(pushManager, /Notification\.requestPermission/);
  assert.match(pushManager, /주문·배송 알림/);
  assert.match(page, /MobilePushManager/);
  assert.match(page, /결제완료 Excel/);
  assert.match(page, /buildPaidOrdersExcelWorkbook\(displayOrders\)/);
  assert.match(styles, /@media \(max-width: 1360px\)/);
  assert.match(styles, /@media \(max-width: 1180px\)/);
  assert.match(styles, /@media \(max-width: 900px\)/);
  assert.match(styles, /@media \(max-width: 720px\)/);
  assert.match(styles, /@media \(max-width: 480px\)/);
  assert.match(operationsStyles, /SellerPilot Commerce Control · 2026-08-16/);
  assert.match(operationsStyles, /--primary: #e85d04/);
  assert.match(operationsStyles, /\.commerce-service-rail/);
  assert.match(styles, /\.ticket-list \{ display: block; max-height: 360px/);
  assert.match(styles, /\.publish-channel-list \{ grid-template-columns: 1fr/);
  assert.match(storyboard, /핵심 사용자 여정/);
  assert.match(storyboard, /단계별 구축 범위/);
  const acceptanceRaw = acceptanceData.slice(acceptanceData.indexOf("const rawSections"), acceptanceData.indexOf("// 화면·계산"));
  assert.equal((acceptanceRaw.match(/\["/g) ?? []).length, 175);
  assert.match(acceptanceData, /PostgreSQL 중앙DB와 접근차단/);
  assert.match(acceptanceData, /10,000건 동시주문 시뮬레이션/);
  assert.match(acceptancePage, /PPT 31장 기반 · 175개 인수 항목/);
  assert.match(acceptancePage, /화면 완성과 실제 작동을/);
  assert.match(readinessPage, /로그인됐다는 사실과/);
  assert.match(readinessPage, /resolvedReadiness\.length/);
  assert.match(readinessPage, /resolveChannelReadiness/);
  assert.match(readinessPage, /consoleVerifiedChannels/);
  assert.doesNotMatch(readinessPage, /2 \/ 6|0 \/ 6|6개 활성 판매채널/);
  assert.match(readinessPage, /QSM 개별 상품등록 필드 맵/);
  assert.match(readinessPage, /인증 키 읽기 통과/);
  assert.match(readinessPage, /apiReadPassed\} \/ \{resolvedReadiness\.length\}/);
  assert.match(readinessPage, /LAST CONSOLE SNAPSHOT/);
  assert.match(readinessPage, /LIVE DB MERGED/);
  assert.match(readinessData, /Shopee Open Platform/);
  assert.match(readinessData, /Access 4시간 · Refresh 30일/);
  assert.match(readinessData, /Test·Live 모두 https:\/\/sellerpilot-global\.vercel\.app 반영/);
  assert.match(readinessData, /운영 키 v6/);
  assert.match(readinessData, /orders\.list 최근 변경 주문 조회 HTTP 200/);
  assert.match(readinessData, /Security Questionnaire 승인/);
  assert.match(readinessData, /재제출 전 마지막 스냅샷/);
  assert.doesNotMatch(readinessData, /컴플라이언스 2개 항목 보완 대기/);
  assert.doesNotMatch(readinessData, /불완전으로 Rejected/);
  assert.match(readinessData, /11번가 Seller Office · OPEN API/);
  assert.match(readinessData, /운영 API Key/);
  assert.match(readinessPage, /현재 Vault·인증 키 읽기·주문\/문의 게이트웨이 상태를 분리해 병합/);
  assert.match(readinessData, /Access 30일 · Refresh 180일/);
  assert.match(readinessData, /대표 1장, 추가 최대 50장, 동영상 최대 1개/);
  assert.match(channelMapping, /Qoo10 QSM 실제 상품등록 필드/);
  assert.match(channelMapping, /Shopee Open Platform 준비도/);
  assert.match(channelMapping, /Lazada Open Platform/);
  const credentialPage = await readFile(new URL("../app/api-credential-center.tsx", import.meta.url), "utf8");
  assert.match(credentialPage, /고객 문의 목록/);
  assert.match(credentialPage, /배송·물류 API 연결/);
  assert.match(credentialPage, /SmartShip 물류 API 실행 검수/);
  const credentialTestRoute = await readFile(new URL("../app/api/admin/channel-credentials/test/route.ts", import.meta.url), "utf8");
  const gatewayCompleteRoute = await readFile(new URL("../app/api/channel-gateway/worker/complete/route.ts", import.meta.url), "utf8");
  const atomicGatewayCompletionMigration = await readFile(new URL("../supabase/migrations/20260826090400_atomic_gateway_completion_side_effects.sql", import.meta.url), "utf8");
  const aiCompleteRoute = await readFile(new URL("../app/api/ai/worker/complete/route.ts", import.meta.url), "utf8");
  const authCallbackRoute = await readFile(new URL("../app/auth/callback/route.ts", import.meta.url), "utf8");
  const gatewayContract = await readFile(new URL("../lib/channels/gateway-contract.ts", import.meta.url), "utf8");
  const cliRuntimeCard = await readFile(new URL("../app/ai-cli-runtime-card.tsx", import.meta.url), "utf8");
  const cliWorker = await readFile(new URL("../scripts/ai-cli-worker.mjs", import.meta.url), "utf8");
  const cliMigration = await readFile(new URL("../supabase/migrations/20260816065848_sellerpilot_ai_cli_jobs.sql", import.meta.url), "utf8");
  const credentialMigration = await readFile(new URL("../supabase/migrations/20260816060000_channel_credentials_and_roles.sql", import.meta.url), "utf8");
  const operationsMigration = await readFile(new URL("../supabase/migrations/20260816104732_operations_core.sql", import.meta.url), "utf8");
  const operationsRoute = await readFile(new URL("../app/api/operations/snapshot/route.ts", import.meta.url), "utf8");
  const cliControlsMigration = await readFile(new URL("../supabase/migrations/20260816103854_ai_operations_controls.sql", import.meta.url), "utf8");
  assert.match(credentialPage, /Supabase Vault/);
  assert.match(credentialPage, /AI는 Vercel OIDC 서버에서 실행하고 작업 상태는 Supabase 비공개 큐에 저장/);
  assert.doesNotMatch(credentialPage, /Mac의 ChatGPT CLI/);
  assert.match(cliRuntimeCard, /서버 AI 스튜디오 런타임/);
  assert.match(cliRuntimeCard, /SERVER-ONLY VERCEL AI/);
  assert.match(cliRuntimeCard, /authenticatedFetch\("\/api\/ai\/product-studio"\)/);
  assert.doesNotMatch(cliRuntimeCard, /npm run ai:worker:install/);
  assert.match(cliWorker, /codex-image/);
  assert.match(cliWorker, /--enable", "image_generation/);
  assert.doesNotMatch(packageJson, /local-analyzer-server|run-local-demo/);
  assert.match(cliMigration, /sellerpilot_claim_ai_job/);
  assert.match(cliMigration, /sellerpilot-ai/);
  assert.match(cliControlsMigration, /sellerpilot_retry_ai_job/);
  assert.match(cliControlsMigration, /sellerpilot_prune_ai_jobs/);
  assert.match(operationsMigration, /sellerpilot_get_operations_snapshot/);
  assert.match(operationsMigration, /sellerpilot_seed_demo_operations/);
  assert.match(operationsRoute, /margin_save/);
  assert.match(operationsRoute, /ticket_update/);
  assert.match(operationsRoute, /activeSalesChannels\.has\(channel\)/);
  assert.doesNotMatch(credentialPage, /Project API Key|OpenAI API/);
  assert.match(credentialPage, /키 수명 · 교체 일정/);
  assert.match(credentialPage, /연결 검사/);
  assert.match(credentialTestRoute, /parsed\.data\.channel === "shopee"/);
  assert.match(credentialTestRoute, /parsed\.data\.channel === "lazada"/);
  assert.match(credentialTestRoute, /parsed\.data\.channel === "elevenst"/);
  assert.match(gatewayCompleteRoute, /sellerpilot_service_gateway_completion_context/);
  assert.match(gatewayCompleteRoute, /sellerpilot_service_complete_gateway_transaction/);
  assert.match(gatewayCompleteRoute, /p_credential_refresh: credentialRefresh \?\? null/);
  assert.doesNotMatch(gatewayCompleteRoute, /sellerpilot_service_refresh_(?:shopee|lazada|ebay)/);
  assert.doesNotMatch(gatewayCompleteRoute, /sellerpilot_record_credential_test/);
  assert.doesNotMatch(gatewayCompleteRoute, /sellerpilot_service_prepare_gateway_credential_refresh/);
  assert.ok(
    gatewayCompleteRoute.indexOf("sellerpilot_service_gateway_completion_context")
      < gatewayCompleteRoute.indexOf("sellerpilot_service_complete_gateway_transaction"),
  );
  assert.match(atomicGatewayCompletionMigration, /sellerpilot_private\.gateway_completion_receipts/);
  assert.match(atomicGatewayCompletionMigration, /sellerpilot_service_prepare_gateway_credential_refresh/);
  assert.match(atomicGatewayCompletionMigration, /sellerpilot_service_ingest_orders/);
  assert.match(atomicGatewayCompletionMigration, /sellerpilot_service_ingest_inquiries/);
  assert.match(atomicGatewayCompletionMigration, /sellerpilot_record_credential_test/);
  assert.doesNotMatch(gatewayCompleteRoute, /sellerpilot_get_channel_gateway_job/);
  assert.match(aiCompleteRoute, /sellerpilot_service_begin_ai_job_completion/);
  assert.ok(
    aiCompleteRoute.indexOf("sellerpilot_service_begin_ai_job_completion")
      < aiCompleteRoute.indexOf("sellerpilot_complete_ai_job"),
  );
  assert.doesNotMatch(aiCompleteRoute, /storage\.from\("sellerpilot-ai"\)\.remove/);
  assert.match(authCallbackRoute, /safeRelativeReturnPath/);
  assert.doesNotMatch(authCallbackRoute, /startsWith\("\/"\)/);
  assert.match(gatewayContract, /"qoo10", "shopee", "lazada", "coupang", "elevenst", "smartstore", "ebay", "temu"/);
  assert.match(credentialPage, /API 실행 검수/);
  assert.match(credentialPage, /중복 방지 키/);
  assert.match(credentialPage, /confirmWrite/);
  assert.match(credentialMigration, /sellerpilot_rotate_credential/);
  assert.match(credentialMigration, /vault\.create_secret/);
  assert.match(credentialMigration, /sellerpilot_list_credential_audit/);
  assert.match(credentialMigration, /sellerpilot_get_active_credential_secret/);
  const lazadaAuthorizeRoute = await readFile(new URL("../app/api/admin/channel-credentials/lazada/authorize/route.ts", import.meta.url), "utf8");
  const maintenanceRoute = await readFile(new URL("../app/api/internal/maintenance/route.ts", import.meta.url), "utf8");
  const periodicSyncRoute = await readFile(new URL("../app/api/internal/channel-sync/route.ts", import.meta.url), "utf8");
  const manualSyncRoute = await readFile(new URL("../app/api/operations/sync/route.ts", import.meta.url), "utf8");
  const gatewayClaimRoute = await readFile(new URL("../app/api/channel-gateway/worker/claim/route.ts", import.meta.url), "utf8");
  const syncArguments = await readFile(new URL("../lib/channels/sync-arguments.ts", import.meta.url), "utf8");
  const periodicSyncMigration = await readFile(new URL("../supabase/migrations/20260820170000_periodic_channel_sync.sql", import.meta.url), "utf8");
  const releaseIntegrityMigration = await readFile(new URL("../supabase/migrations/20260828210000_non_cs_release_integrity.sql", import.meta.url), "utf8");
  const rotationHardeningMigration = await readFile(new URL("../supabase/migrations/20260821110000_harden_oauth_rotation_and_cleanup_lints.sql", import.meta.url), "utf8");
  const vercelConfig = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
  const refreshMigration = await readFile(new URL("../supabase/migrations/20260816110000_lazada_token_refresh.sql", import.meta.url), "utf8");
  const connectorMigration = await readFile(new URL("../supabase/migrations/20260816120321_expand_channel_connectors.sql", import.meta.url), "utf8");
  const shopeeMigration = await readFile(new URL("../supabase/migrations/20260816133601_add_shopee_connector.sql", import.meta.url), "utf8");
  const channelCatalog = await readFile(new URL("../lib/channels/catalog.ts", import.meta.url), "utf8");
  const channelProtocols = await readFile(new URL("../lib/channels/protocols.ts", import.meta.url), "utf8");
  const channelOperations = await readFile(new URL("../lib/channels/operations.ts", import.meta.url), "utf8");
  const channelOperationsRoute = await readFile(new URL("../app/api/admin/channel-operations/route.ts", import.meta.url), "utf8");
  const channelOperationsContract = await readFile(new URL("../docs/판매채널_실행_API_계약.md", import.meta.url), "utf8");
  const channelTargetClient = await readFile(new URL("../app/channel-target-client.ts", import.meta.url), "utf8");
  const ebayAuthorizeRoute = await readFile(new URL("../app/api/admin/channel-credentials/ebay/authorize/route.ts", import.meta.url), "utf8");
  assert.match(lazadaAuthorizeRoute, /sellerpilot_lazada_oauth/);
  assert.match(lazadaAuthorizeRoute, /timingSafeEqual/);
  assert.match(lazadaAuthorizeRoute, /response\.cookies\.set/);
  assert.match(lazadaAuthorizeRoute, /p_environment: credentialEnvironment/);
  assert.match(maintenanceRoute, /sellerpilot_enqueue_channel_gateway_job/);
  assert.doesNotMatch(maintenanceRoute, /sellerpilot_service_refresh_(?:shopee|lazada|ebay)/);
  assert.match(periodicSyncRoute, /sellerpilot_service_enqueue_periodic_sync/);
  assert.match(periodicSyncRoute, /sellerpilot_service_validate_worker_token/);
  assert.match(periodicSyncRoute, /createBoundedSupabaseFetch/);
  assert.match(periodicSyncRoute, /PERIODIC_SYNC_ENQUEUE_CONCURRENCY = 5/);
  assert.match(periodicSyncRoute, /mapWithConcurrency\(queueRequests, PERIODIC_SYNC_ENQUEUE_CONCURRENCY/);
  assert.match(periodicSyncRoute, /reconciliationRequired/);
  assert.match(gatewayClaimRoute, /workerRpcErrorStatus/);
  assert.match(cliWorker, /authBackoffUntil/);
  assert.match(cliWorker, /gatewayClaimBackoffUntil/);
  assert.equal((manualSyncRoute.match(/gatewayChannels\.has\(channel\)/g) ?? []).length, 2);
  assert.doesNotMatch(manualSyncRoute, /channel === "coupang" \|\| channel === "smartstore" \|\| channel === "lazada"/);
  assert.match(manualSyncRoute, /if \(!parsed\.data\.includeImBootstrap && parsed\.data\.historyDays === undefined\)[\s\S]{0,520}delegated: true[\s\S]{0,520}status: 409/);
  assert.match(manualSyncRoute, /sellerpilot_start_inquiry_history_backfill/);
  assert.match(manualSyncRoute, /sellerpilot_get_inquiry_history_backfill/);
  assert.match(manualSyncRoute, /export async function GET\(request: Request\)/);
  assert.doesNotMatch(manualSyncRoute, /inquiryHistorySyncRequests/);
  assert.match(manualSyncRoute, /parsed\.data\.channels\.includes\("coupang"\)/);
  assert.match(manualSyncRoute, /parsed\.data\.channels\.includes\("smartstore"\)/);
  assert.match(manualSyncRoute, /export const maxDuration = 300/);
  assert.match(manualSyncRoute, /!credentials\.some\(\(credential\) => credential\.channel === "coupang"\)[\s\S]{0,180}!credentials\.some\(\(credential\) => credential\.channel === "smartstore"\)[\s\S]{0,420}status: 409/);
  assert.match(manualSyncRoute, /historyBackfillResultSchema/);
  assert.match(manualSyncRoute, /parsedResult\.data\.status === "failed" \? 207 : 202/);
  assert.match(syncArguments, /partnerCounselingStatus of \["NONE", "ANSWER", "NO_ANSWER", "TRANSFER"\]/);
  assert.match(syncArguments, /const fromDate = koreaCalendarDate\(from\)/);
  assert.match(syncArguments, /const toDate = koreaCalendarDate\(now\)/);
  assert.doesNotMatch(syncArguments, /if \(channel === "elevenst"\)[^\n]*inquir/i);
  assert.equal((manualSyncRoute.match(/sellerpilot_service_enqueue_periodic_sync/g) ?? []).length, 2);
  assert.doesNotMatch(manualSyncRoute, /sellerpilot_enqueue_channel_gateway_job/);
  assert.match(manualSyncRoute, /MANUAL_SYNC_ENQUEUE_CONCURRENCY = 4/);
  assert.match(manualSyncRoute, /MANUAL_SYNC_RPC_TIMEOUT_MS = 8_000/);
  assert.match(manualSyncRoute, /authenticateAdminRequest\(request, \{ timeoutMs: MANUAL_SYNC_RPC_TIMEOUT_MS \}\)/);
  assert.equal((manualSyncRoute.match(/runPeriodicEnqueueRpc\(\(\) => admin\.serviceClient\.rpc\("sellerpilot_service_enqueue_periodic_sync"/g) ?? []).length, 2);
  assert.match(manualSyncRoute, /status: needsAttention \? 207 : 200/);
  assert.match(manualSyncRoute, /result\.status === "reconciliation_required"/);
  assert.match(page, /쿠팡·스마트스토어 30일/);
  assert.match(page, /cs-history-backfill/);
  assert.match(page, /첫 작업 성공만으로 전체 완료 처리하지 않습니다/);
  assert.match(page, /refreshInquiryHistoryBackfill/);
  assert.match(page, /window\.setInterval\(refreshWhenVisible, 15_000\)/);
  assert.match(mobileStyles, /\.cs-history-counts[\s\S]{0,120}grid-template-columns: repeat\(2/);
  assert.match(periodicSyncRoute, /orderSyncRequests/);
  assert.doesNotMatch(periodicSyncRoute, /inquirySyncRequests|periodicInquiryRequests|blockedInquiryResults/);
  assert.match(syncArguments, /"ACCEPT", "INSTRUCT", "DEPARTURE", "DELIVERING", "FINAL_DELIVERY"/);
  assert.match(syncArguments, /"0", "3", "4", "5"/);
  assert.match(syncArguments, /SearchStartDate/);
  assert.match(syncArguments, /search_start_dt/);
  assert.match(periodicSyncRoute, /dispatchPendingPushNotifications/);
  assert.match(periodicSyncMigration, /already_pending/);
  assert.match(periodicSyncMigration, /'qoo10', 'shopee', 'lazada', 'coupang', 'smartstore', 'ebay', 'temu'/);
  assert.doesNotMatch(vercelConfig, /\/api\/internal\/(?:channel-sync|product-research|competitor-prices|kakao-notifications)/);
  assert.match(releaseIntegrityMigration, /sellerpilot-channel-sync-v1'[\s\S]{0,80}'1-59\/5 \* \* \* \*'/);
  assert.match(releaseIntegrityMigration, /sellerpilot-kakao-notifications-v1'[\s\S]{0,80}'4-59\/5 \* \* \* \*'/);
  assert.match(cliWorker, /SELLERPILOT_CHANNEL_SYNC_MS/);
  assert.match(cliWorker, /\/api\/internal\/channel-sync/);
  assert.match(cliWorker, /sellerpilot-cli-worker\/1\.60/);
  assert.match(cliWorker, /ensureEbayAccessToken/);
  assert.match(rotationHardeningMigration, /diagnostic_preserved/);
  assert.match(rotationHardeningMigration, /status = 'queued' and attempt_id is null/);
  assert.match(refreshMigration, /token_refreshed/);
  assert.match(connectorMigration, /coupang.*elevenst.*smartstore.*ebay/);
  assert.match(connectorMigration, /sellerpilot_service_refresh_ebay/);
  assert.match(shopeeMigration, /sellerpilot_service_refresh_shopee/);
  assert.match(shopeeMigration, /'qoo10', 'shopee', 'lazada'/);
  assert.equal((channelCatalog.match(/key: "(?:qoo10|shopee|lazada|coupang|elevenst|smartstore|ebay|temu)"/g) ?? []).length, 8);
  assert.match(channelCatalog, /ProductSearch 1건 읽기/);
  assert.match(channelCatalog, /temu\.local\.goods\.v3\.add/);
  assert.match(channelProtocols, /CEA algorithm=HmacSHA256/);
  assert.match(channelProtocols, /replace\(\/%3A\/gi, ":"\)/);
  assert.match(channelProtocols, /client_secret_sign/);
  assert.match(channelProtocols, /ebayjapan\.qapi/);
  assert.match(channelProtocols, /buildShopeeSignature/);
  assert.match(channelProtocols, /ensureShopeeAccessToken/);
  assert.match(channelOperations, /executeChannelOperation/);
  assert.match(channelOperations, /\/product\/price_quantity\/update/);
  assert.match(channelOperations, /\/v2\/products\/origin-products/);
  assert.match(channelOperations, /shipping_fulfillment/);
  assert.match(channelOperationsRoute, /confirmWrite/);
  assert.match(channelOperationsRoute, /idempotencyKey/);
  assert.match(channelOperationsRoute, /sellerpilot_claim_channel_operation/);
  assert.match(channelOperationsRoute, /executeViaChannelGateway/);
  assert.doesNotMatch(channelOperationsRoute, /ensureEbayAccessToken/);
  assert.match(channelTargetClient, /cached\.status === 401/);
  assert.match(channelTargetClient, /request\("POST"\)/);
  assert.match(channelTargetClient, /pendingTargetRequests/);
  assert.match(connectorMigration, /channel_operation_attempts/);
  assert.match(connectorMigration, /sellerpilot_claim_channel_operation/);
  assert.match(connectorMigration, /sellerpilot_service_complete_channel_operation/);
  assert.match(channelOperationsContract, /`POST \/api\/admin\/channel-operations`/);
  assert.match(ebayAuthorizeRoute, /sellerpilot_ebay_oauth/);
  const shopeeAuthorizeRoute = await readFile(new URL("../app/api/admin/channel-credentials/shopee/authorize/route.ts", import.meta.url), "utf8");
  assert.match(shopeeAuthorizeRoute, /sellerpilot_shopee_oauth/);
  assert.match(shopeeAuthorizeRoute, /timingSafeEqual/);
  for (const protectedPattern of [/authorization[_ ]?code\s*[:=]/i, /access[_ ]?token\s*[:=]/i, /app[_ ]?secret\s*[:=]/i, /partner[_ ]?key\s*[:=]/i]) {
    assert.doesNotMatch(`${readinessData}\n${channelMapping}`, protectedPattern);
  }
  assert.match(packageJson, /lucide-react/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
