import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';import{readFile}from'node:fs/promises';
import {tsImport} from 'tsx/esm/api';
const {getSafeSignInError}=await tsImport('../lib/auth-sign-in-error-safety.ts',import.meta.url);
const source=await readFile(new URL('../app/page.tsx',import.meta.url),'utf8');const ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const fn=name=>ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);
const run=(text,context)=>vm.runInNewContext(ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.None}}).outputText,context);
test('real LoginScreen submit releases loading and classifies thrown Auth 504',async()=>{const statement=fn('LoginScreen').body.statements.find(n=>ts.isVariableStatement(n)&&n.declarationList.declarations[0].name.getText(ast)==='submit');const loading=[],errors=[];const submit=run(statement.getText(ast)+';submit;', {sessionCleanupPending:false,email:' fixture@example.test ',password:'fixture',setLoading:v=>loading.push(v),setError:v=>errors.push(v),onLogin:async()=>{throw {status:504,message:'PRIVATE RAW ERROR'};},getSafeSignInError});await submit({preventDefault(){}});assert.deepEqual(loading,[true,false]);assert.equal(errors.at(-1),getSafeSignInError({status:504}));assert.ok(!errors.join('').includes('PRIVATE'));});
const callback=fn('Home').body.statements.find(n=>n.getText(ast).startsWith('useEffect(')&&n.getText(ast).includes('completeChannelOAuth'));
async function complete(state,stored){let finish;const done=new Promise(r=>finish=r);const calls=[],messages=[];const context={accessState:'admin',userId:'owner',pendingChannelOAuth:{channel:'shopee',state,code:'fixture-code',mainAccountId:'123456',shopId:'SPOOF'},oauthHandled:{current:false},createSupabaseClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'owner'},access_token:'fixture-only'}}})}}),readShopeeExactBrowserSession:()=>stored,setOAuthToastMessage:v=>messages.push(v),setPendingChannelOAuth:()=>finish(),useEffect:f=>f(),fetch:async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return{ok:true,json:async()=>({status:'bound'})};},AbortSignal,window:{sessionStorage:{removeItem(){}}},shopeeExactBrowserKey:'fixture'};run(callback.getText(ast),context);await done;return{calls,messages};}
test('legacy Shopee callback cannot fall through to generic authorize',async()=>{const r=await complete('sellerpilot-shopee-legacy',{sessionId:'session',credentialId:'credential'});assert.equal(r.calls.length,0);assert.match(r.messages[0],/차단/);});
test('missing exact browser session cannot exchange provider code',async()=>{const r=await complete('sellerpilot-shopee-exact-fixture',null);assert.equal(r.calls.length,0);});
test('exact callback calls bind only, excludes shop spoof, reports bound not recovered',async()=>{const r=await complete('sellerpilot-shopee-exact-fixture',{sessionId:'session',credentialId:'credential'});assert.equal(r.calls.length,1);assert.equal(r.calls[0].url,'/api/admin/channel-credentials/shopee/exact');assert.equal(r.calls[0].body.action,'bind');assert.equal(r.calls[0].body.mainAccountId,'123456');assert.equal(r.calls[0].body.shop_id,undefined);assert.match(r.messages[0],/연결 완료 전/);});
test('root login delegates all returned Auth errors to safe helper',()=>{const login=fn('Home').body.statements.find(n=>ts.isVariableStatement(n)&&n.declarationList.declarations[0].name.getText(ast)==='login');assert.match(login.getText(ast),/if \(error\) return getSafeSignInError\(error\)/);});
test('real root start handler prepares then uses exact readiness, never general authorize',async()=>{
 const statement=fn('Home').body.statements.find(n=>n.getText(ast).startsWith('useEffect(')&&n.getText(ast).includes('sellerpilot:shopee-exact-start'));
 const calls=[],messages=[];let listener,stored,assigned;const owner='11111111-1111-4111-8111-111111111111',credentialId='22222222-2222-4222-8222-222222222222';
 run(statement.getText(ast),{accessState:'admin',userId:owner,exactStarting:{current:false},useEffect:f=>f(),readShopeeExactBrowserSession:()=>stored,shopeeExactBrowserKey:'fixture',createSupabaseClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:owner},access_token:'fixture-only-token'}}})}}),fetch:async(url,init)=>{const body=JSON.parse(init.body);calls.push({url,body});return{ok:true,json:async()=>body.action==='prepare'?{status:'executor_required',sessionId:'33333333-3333-4333-8333-333333333333'}:{status:'ready',authorizationUrl:'https://open.shopee.com/auth?state=sellerpilot-shopee-exact-fixture'}};},setOAuthToastMessage:v=>messages.push(v),window:{addEventListener:(_,fn)=>listener=fn,removeEventListener(){},sessionStorage:{setItem:(_,v)=>stored=JSON.parse(v)},location:{assign:v=>assigned=v}},URL,AbortSignal});
 listener({detail:{credentialId}});await new Promise(setImmediate);assert.equal(calls[0].body.action,'prepare');assert.equal(assigned,undefined);assert.equal(stored.ownerId,owner);assert.ok(!JSON.stringify(stored).includes('token'));
 listener({detail:{credentialId}});await new Promise(setImmediate);assert.deepEqual(calls.map(c=>c.body.action),['prepare','start']);assert.ok(calls.every(c=>c.url==='/api/admin/channel-credentials/shopee/exact'));assert.match(assigned,/^https:\/\/open.shopee.com\/auth/);
});
test('credential-center Shopee button dispatches root event and returns before legacy auth fetch',async()=>{
 const text=await readFile(new URL('../app/api-credential-center.tsx',import.meta.url),'utf8');const tree=ts.createSourceFile('center.tsx',text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let declaration;
 const visit=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(tree)==='startOAuth')declaration=n;ts.forEachChild(n,visit);};visit(tree);assert.ok(declaration);
 const events=[];let fetches=0;const start=run('const '+declaration.getText(tree)+';startOAuth;', {setPendingOAuth(){},setError(){},window:{dispatchEvent:e=>events.push(e)},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init.detail;}},fetch:()=>{fetches++;throw Error('legacy must not run');}});
 await start({id:'fixture-id',channel:'shopee'});assert.equal(fetches,0);assert.equal(events[0].type,'sellerpilot:shopee-exact-start');assert.equal(events[0].detail.credentialId,'fixture-id');
});
