export const aiGeneratedAssetSpecs = [
  { id: "hero", file: "hero.png", role: "gallery", label: "clean ecommerce product hero", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, centered, filling 72–82% of the frame, clean neutral studio background, complete package visible", scene: "neutral seamless studio sweep with a restrained pedestal and one soft contact shadow", camera: "eye-level front three-quarter catalog camera" },
  { id: "square", file: "thumbnail-square.png", role: "gallery", label: "marketplace primary thumbnail", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, centered, filling 78–86% of the square frame, front-facing catalog composition, complete silhouette visible", scene: "pure white or extremely pale neutral catalog background without props", camera: "straight-on orthographic-looking product camera" },
  { id: "portrait", file: "thumbnail-portrait.png", role: "creative", label: "mobile portrait setting shot", ratio: "4:5", width: 1200, height: 1500, referenceRoles: ["main", "front", "left", "right", "top"], composition: "vertical real-world setting shot, product filling 58–70% of the frame, complete package in the upper two-thirds, assigned place clearly visible", scene: "the first assigned product-specific real environment, never a colored studio wall or geometric set", camera: "slightly low three-quarter environmental camera with vertical spatial depth" },
  { id: "wide", file: "thumbnail-wide.png", role: "creative", label: "wide product setting shot", ratio: "16:9", width: 1600, height: 900, referenceRoles: ["main", "front", "left", "right"], composition: "wide real-world setting shot, product filling at least 48% of the frame, assigned activity area readable across the frame", scene: "the second assigned product-specific real environment in a different location and moment from portrait", camera: "wide eye-level environmental camera with a left-to-right activity path" },
  { id: "detail-overview", file: "detail-overview.png", role: "detail", label: "detail page environmental overview", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "back"], composition: "one complete product in its assigned storage or preparation environment, filling 58–70% of the square frame, product and environmental relationship immediately readable", scene: "the third assigned product-specific real environment, focused on storage or preparation rather than active use", camera: "30-degree environmental overview camera showing both product and place" },
  { id: "detail-feature", file: "detail-feature.png", role: "detail", label: "detail page visible feature close-up", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "label", "front", "left", "right", "top"], composition: "close product crop showing only features visibly supported by the reference, product filling 72–86% of the square frame", scene: "tight material or construction detail with shallow depth and no full-front catalog composition", camera: "macro or close-focus oblique camera" },
  { id: "detail-use", file: "detail-use.png", role: "detail", label: "detail page use context", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "extra"], composition: "realistic use context appropriate to the product, product remains dominant and fills at least 55% of the square frame, no people unless visible in the reference", scene: "credible category-specific use environment with functional surrounding objects and clear spatial context", camera: "medium environmental camera showing the product in use context" },
  { id: "detail-package", file: "detail-package.png", role: "detail", label: "detail page package and included item view", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "back", "label", "barcode", "top", "bottom"], composition: "complete package or included item arrangement supported by the reference, centered and filling 65–78% of the square frame", scene: "top-down flat lay of only the confirmed package and included items; if only one item exists, show the one item beside its real package without duplicating it", camera: "true overhead flat-lay camera" },
] as const;

export type AiGeneratedAssetId = (typeof aiGeneratedAssetSpecs)[number]["id"];

export const aiGeneratedAssetIds = aiGeneratedAssetSpecs.map((asset) => asset.id) as [AiGeneratedAssetId, ...AiGeneratedAssetId[]];

export const aiDetailAssetIds = aiGeneratedAssetSpecs
  .filter((asset) => asset.role === "detail")
  .map((asset) => asset.id) as AiGeneratedAssetId[];

export function aiGeneratedAssetPath(jobId: string, asset: (typeof aiGeneratedAssetSpecs)[number]) {
  return `results/${jobId}/${asset.file}`;
}
