export const aiGeneratedAssetSpecs = [
  { id: "hero", file: "hero.png", role: "gallery", label: "clean ecommerce product hero", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, centered, filling 72–82% of the frame, clean neutral studio background, complete package visible", scene: "neutral seamless studio sweep with a restrained pedestal and one soft contact shadow", camera: "eye-level front three-quarter catalog camera" },
  { id: "square", file: "thumbnail-square.png", role: "gallery", label: "marketplace primary thumbnail", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, centered, filling 78–86% of the square frame, front-facing catalog composition, complete silhouette visible", scene: "pure white or extremely pale neutral catalog background without props", camera: "straight-on orthographic-looking product camera" },
  { id: "portrait", file: "thumbnail-portrait.png", role: "creative", label: "mobile portrait thumbnail", ratio: "4:5", width: 1200, height: 1500, referenceRoles: ["main", "front", "left", "right", "top"], composition: "vertical editorial product layout, product filling 62–72% of the frame, complete package in the upper two-thirds", scene: "vertical editorial set with a tall color field and one category-relevant surface element", camera: "slightly low three-quarter camera with vertical negative space" },
  { id: "wide", file: "thumbnail-wide.png", role: "creative", label: "wide promotion thumbnail", ratio: "16:9", width: 1600, height: 900, referenceRoles: ["main", "front", "left", "right"], composition: "wide product composition, product filling at least 52% of the frame, uncluttered supporting surface", scene: "horizontal lifestyle-adjacent set with asymmetrical negative space and no text", camera: "wide eye-level three-quarter camera" },
  { id: "detail-overview", file: "detail-overview.png", role: "detail", label: "detail page product overview", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "back"], composition: "one complete product in a realistic ecommerce studio scene, filling 62–72% of the square frame, clear front and material visibility", scene: "category-appropriate overview set with the complete product and package relationship immediately readable", camera: "eye-level 30-degree three-quarter overview camera" },
  { id: "detail-feature", file: "detail-feature.png", role: "detail", label: "detail page visible feature close-up", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "label", "front", "left", "right", "top"], composition: "close product crop showing only features visibly supported by the reference, product filling 72–86% of the square frame", scene: "tight material or construction detail with shallow depth and no full-front catalog composition", camera: "macro or close-focus oblique camera" },
  { id: "detail-use", file: "detail-use.png", role: "detail", label: "detail page use context", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "extra"], composition: "realistic use context appropriate to the product, product remains dominant and fills at least 55% of the square frame, no people unless visible in the reference", scene: "credible category-specific use environment with functional surrounding objects and clear spatial context", camera: "medium environmental camera showing the product in use context" },
  { id: "detail-package", file: "detail-package.png", role: "detail", label: "detail page package and included item view", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "back", "label", "barcode", "top", "bottom"], composition: "complete package or included item arrangement supported by the reference, centered and filling 65–78% of the square frame", scene: "top-down flat lay of only the confirmed package and included items; if only one item exists, show the one item beside its real package without duplicating it", camera: "true overhead flat-lay camera" },
] as const;

export type AiGeneratedAssetId = (typeof aiGeneratedAssetSpecs)[number]["id"];

export const aiGeneratedAssetIds = aiGeneratedAssetSpecs.map((asset) => asset.id) as [AiGeneratedAssetId, ...AiGeneratedAssetId[]];

export const aiDetailAssetIds = aiGeneratedAssetSpecs
  .filter((asset) => asset.role === "detail")
  .map((asset) => asset.id) as AiGeneratedAssetId[];

export function aiGeneratedAssetPath(jobId: string, asset: (typeof aiGeneratedAssetSpecs)[number]) {
  return `results/${jobId}/${asset.file}`;
}
