export const aiGeneratedAssetSpecs = [
  { id: "hero", file: "hero.png", role: "gallery", label: "clean ecommerce product hero", purpose: "brand-led representative image that establishes premium product identity", shotClass: "asymmetric-front-three-quarter-hero", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, positioned on the right visual third, filling 72–82% of the frame, complete package visible, with intentional clean negative space on the left", subjectPlacement: "right third on a low pedestal with open negative space to the left", scene: "warm light-neutral seamless studio sweep with a restrained low pedestal and one directional soft contact shadow", camera: "eye-level 35mm front three-quarter camera from the product's left side", mustDifferFrom: ["square", "detail-feature", "detail-package"], identityPolicy: { mode: "source-catalog", sourceRoles: ["main", "front"], background: "#f7f3ed", placement: { left: 0.26, top: 0.08, width: 0.70, height: 0.84 } } },
  { id: "square", file: "thumbnail-square.png", role: "gallery", label: "marketplace primary thumbnail", purpose: "literal front identification image for marketplace search results", shotClass: "centered-straight-on-white-catalog", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right"], composition: "one product only, dead centered, filling 78–86% of the square frame, straight-on front catalog composition, complete silhouette visible and symmetric margins", subjectPlacement: "dead center with equal four-side margins and no pedestal", scene: "pure white shadow-minimal catalog background without props, gradient, horizon line or pedestal", camera: "straight-on 70mm orthographic-looking front product camera at label height", mustDifferFrom: ["hero", "detail-feature", "detail-package"], identityPolicy: { mode: "source-catalog", sourceRoles: ["main", "front"], background: "#ffffff", placement: { left: 0.07, top: 0.07, width: 0.86, height: 0.86 } } },
  { id: "portrait", file: "thumbnail-portrait.png", role: "creative", label: "mobile portrait setting shot", purpose: "vertical lifestyle discovery image that establishes the first real use setting", shotClass: "vertical-environmental-setting", ratio: "4:5", width: 1200, height: 1500, referenceRoles: ["main", "front", "left", "right", "top"], composition: "vertical real-world setting shot, product filling 58–70% of the frame, complete package in the upper two-thirds, assigned place clearly visible", subjectPlacement: "assigned product-specific portrait placement, never centered like square", scene: "the first assigned product-specific real environment, never a colored studio wall or geometric set", camera: "the product-specific portrait camera assigned by the setting-shot plan", mustDifferFrom: ["hero", "square", "wide", "detail-overview", "detail-use"], identityPolicy: { mode: "source-composite", sourceRoles: ["main", "front", "extra"], background: "#f5f1ea", placement: { left: 0.08, top: 0.10, width: 0.62, height: 0.74 } } },
  { id: "wide", file: "thumbnail-wide.png", role: "creative", label: "wide product setting shot", purpose: "horizontal activity narrative showing how the product enters a real task", shotClass: "horizontal-activity-setting", ratio: "16:9", width: 1600, height: 900, referenceRoles: ["main", "front", "left", "right"], composition: "wide real-world setting shot, product filling at least 48% of the frame, assigned activity area readable across the frame", subjectPlacement: "assigned far-side product position with a long activity path across the opposite side", scene: "the second assigned product-specific real environment in a different location and moment from portrait", camera: "the product-specific wide camera assigned by the setting-shot plan", mustDifferFrom: ["portrait", "detail-overview", "detail-use"], identityPolicy: { mode: "source-composite", sourceRoles: ["left", "right", "back", "extra"], background: "#f3efe7", placement: { left: 0.61, top: 0.10, width: 0.34, height: 0.78 } } },
  { id: "detail-overview", file: "detail-overview.png", role: "detail", label: "detail page environmental overview", purpose: "whole-product storage or preparation overview that explains scale and organization", shotClass: "high-environmental-overview", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "back"], composition: "one complete product in its assigned storage or preparation environment, filling 58–70% of the square frame, product and environmental relationship immediately readable", subjectPlacement: "assigned rear or central storage position with readable empty foreground depth", scene: "the third assigned product-specific real environment, focused on storage or preparation rather than active use", camera: "environmental overview camera using the product-specific high rear angle assigned by the setting-shot plan", mustDifferFrom: ["hero", "square", "portrait", "wide", "detail-feature", "detail-use", "detail-package"], identityPolicy: { mode: "source-composite", sourceRoles: ["back", "top", "left", "right", "extra"], background: "#f6f4ef", placement: { left: 0.18, top: 0.14, width: 0.56, height: 0.70 } } },
  { id: "detail-feature", file: "detail-feature.png", role: "detail", label: "source label and visible-feature close-up", purpose: "source-pixel evidence of visible front label, material and construction without inferred claims", shotClass: "source-front-feature-crop", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "label", "front", "left", "right"], composition: "a close source-pixel crop of the verified front package or visible product feature; retain only facts physically present in the selected source and never reconstruct hidden areas", subjectPlacement: "verified source pixels fill the square crop while printed marks remain unaltered", scene: "plain neutral evidence canvas without generated product pixels or lifestyle staging", camera: "direct crop from the verified source view; no synthetic camera rotation", mustDifferFrom: ["hero", "square", "detail-overview", "detail-package"], identityPolicy: { mode: "source-evidence", sourceRoles: ["label", "front", "main"], background: "#fafafa", fit: "cover", placement: { left: 0.03, top: 0.03, width: 0.94, height: 0.94 } } },
  { id: "detail-use", file: "detail-use.png", role: "detail", label: "detail page use context", purpose: "active-use evidence image showing the product's verified functional outcome", shotClass: "active-use-environment", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["main", "front", "left", "right", "extra"], composition: "realistic use context appropriate to the product, product remains dominant and fills at least 55% of the square frame, no people unless visible in the reference", subjectPlacement: "assigned product-specific use position separated in depth from the verified functional result", scene: "the fourth assigned category-specific environment with functional surrounding objects and clear spatial context", camera: "medium environmental camera using the product-specific table-level angle assigned by the setting-shot plan", mustDifferFrom: ["hero", "square", "portrait", "wide", "detail-overview", "detail-feature", "detail-package"], identityPolicy: { mode: "source-composite", sourceRoles: ["label", "bottom", "left", "right", "extra"], background: "#f2ede4", placement: { left: 0.54, top: 0.28, width: 0.42, height: 0.64 } } },
  { id: "detail-package", file: "detail-package.png", role: "detail", label: "source side or rear package evidence", purpose: "factual source-pixel evidence of an actually supplied side, rear, label or barcode panel", shotClass: "source-side-rear-evidence", ratio: "1:1", width: 1200, height: 1200, referenceRoles: ["back", "label", "barcode", "top", "bottom", "left", "right", "extra", "main"], composition: "show only the selected supplied side, rear, label or barcode source view; do not claim a top closure, hidden plane or package structure unless it is visible in that exact source", subjectPlacement: "selected evidence panel centered with enough margin to keep its source pixels readable", scene: "plain cool neutral evidence canvas without lifestyle props, synthetic rotation or generated product pixels", camera: "direct crop from the selected supplied evidence view; no inferred high-oblique camera", mustDifferFrom: ["hero", "square", "detail-overview", "detail-feature"], identityPolicy: { mode: "source-evidence", sourceRoles: ["back", "label", "barcode", "top", "bottom", "left", "right", "extra"], requiresDedicatedRole: true, background: "#f3f5f6", placement: { left: 0.08, top: 0.08, width: 0.84, height: 0.84 } } },
] as const;

export type AiGeneratedAssetId = (typeof aiGeneratedAssetSpecs)[number]["id"];

export const aiGeneratedAssetIds = aiGeneratedAssetSpecs.map((asset) => asset.id) as [AiGeneratedAssetId, ...AiGeneratedAssetId[]];

export const aiDetailAssetIds = aiGeneratedAssetSpecs
  .filter((asset) => asset.role === "detail")
  .map((asset) => asset.id) as AiGeneratedAssetId[];

export function aiGeneratedAssetPath(
  jobId: string,
  asset: (typeof aiGeneratedAssetSpecs)[number],
  claimToken?: string,
) {
  return claimToken
    ? `results/${jobId}/claims/${claimToken}/${asset.file}`
    : `results/${jobId}/${asset.file}`;
}
