WITH ns AS (
 SELECT oid,nspname FROM pg_namespace WHERE nspname IN ('public','sellerpilot_private','auth','storage','extensions')
), ext AS (SELECT objid,classid FROM pg_depend WHERE deptype='e'),
rels AS (SELECT c.*,n.nspname,format('%I.%I',n.nspname,c.relname) ident FROM pg_class c JOIN ns n ON n.oid=c.relnamespace WHERE NOT EXISTS(SELECT 1 FROM ext e WHERE e.classid='pg_class'::regclass AND e.objid=c.oid)),
funcs AS (SELECT p.*,n.nspname FROM pg_proc p JOIN ns n ON n.oid=p.pronamespace WHERE p.prokind IN ('f','p') AND NOT EXISTS(SELECT 1 FROM ext e WHERE e.classid='pg_proc'::regclass AND e.objid=p.oid)),
collations AS (SELECT co.*,n.nspname FROM pg_collation co JOIN ns n ON n.oid=co.collnamespace WHERE NOT EXISTS(SELECT 1 FROM ext e WHERE e.classid='pg_collation'::regclass AND e.objid=co.oid)),
objects AS (
 SELECT 10 phase,'schema' kind,nspname identity,format('CREATE SCHEMA IF NOT EXISTS %I;',nspname) ddl FROM ns
 UNION ALL SELECT 15,'collation',format('%I.%I',co.nspname,co.collname),format('CREATE COLLATION %I.%I (provider = %s, %s, deterministic = %s%s%s);',co.nspname,co.collname,CASE co.collprovider WHEN 'i' THEN 'icu' WHEN 'c' THEN 'libc' WHEN 'b' THEN 'builtin' END,CASE WHEN co.collprovider='c' THEN format('lc_collate = %L, lc_ctype = %L',co.collcollate,co.collctype) ELSE format('locale = %L',co.colllocale) END,co.collisdeterministic::text,CASE WHEN co.collicurules IS NULL THEN '' ELSE format(', rules = %L',co.collicurules) END,CASE WHEN co.collversion IS NULL THEN '' ELSE format(', version = %L',co.collversion) END) FROM collations co
 UNION ALL SELECT 20,'enum',format('%I.%I',n.nspname,t.typname),format('CREATE TYPE %I.%I AS ENUM (%s);',n.nspname,t.typname,(SELECT string_agg(quote_literal(enumlabel),',' ORDER BY enumsortorder) FROM pg_enum WHERE enumtypid=t.oid)) FROM pg_type t JOIN ns n ON n.oid=t.typnamespace WHERE t.typtype='e'
 UNION ALL SELECT 30,'sequence',c.ident,format('CREATE SEQUENCE %s AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s %s;',c.ident,format_type(s.seqtypid,NULL),s.seqincrement,s.seqmin,s.seqmax,s.seqstart,s.seqcache,CASE WHEN s.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END) FROM rels c JOIN pg_sequence s ON s.seqrelid=c.oid WHERE NOT EXISTS(SELECT 1 FROM pg_depend d WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.deptype='i')
 UNION ALL SELECT 40,'table',c.ident,format('CREATE %s TABLE %s (%s);',CASE WHEN c.relpersistence='u' THEN 'UNLOGGED' ELSE '' END,c.ident,(SELECT string_agg(format('%I %s%s%s',a.attname,format_type(a.atttypid,a.atttypmod)||CASE WHEN a.attcollation<>0 AND a.attcollation<>(SELECT typcollation FROM pg_type WHERE oid=a.atttypid) THEN ' COLLATE '||(SELECT format('%I.%I',n.nspname,co.collname) FROM pg_collation co JOIN pg_namespace n ON n.oid=co.collnamespace WHERE co.oid=a.attcollation) ELSE '' END,CASE WHEN a.attgenerated='s' THEN ' GENERATED ALWAYS AS ('||(SELECT pg_get_expr(d.adbin,d.adrelid) FROM pg_attrdef d WHERE d.adrelid=a.attrelid AND d.adnum=a.attnum)||') STORED' WHEN a.attidentity IN ('a','d') THEN ' GENERATED '||CASE WHEN a.attidentity='a' THEN 'ALWAYS' ELSE 'BY DEFAULT' END||' AS IDENTITY ('||(SELECT format('SEQUENCE NAME %I.%I START WITH %s INCREMENT BY %s MINVALUE %s MAXVALUE %s CACHE %s %s',sn.nspname,sc.relname,seq.seqstart,seq.seqincrement,seq.seqmin,seq.seqmax,seq.seqcache,CASE WHEN seq.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END) FROM pg_depend dep JOIN pg_class sc ON sc.oid=dep.objid JOIN pg_namespace sn ON sn.oid=sc.relnamespace JOIN pg_sequence seq ON seq.seqrelid=sc.oid WHERE dep.classid='pg_class'::regclass AND dep.refclassid='pg_class'::regclass AND dep.refobjid=a.attrelid AND dep.refobjsubid=a.attnum AND dep.deptype='i')||')' ELSE '' END,CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),',' ORDER BY a.attnum) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped)) FROM rels c WHERE c.relkind='r'
 UNION ALL SELECT CASE WHEN EXISTS(SELECT 1 FROM pg_type t WHERE t.oid=f.prorettype AND t.typtype='c') OR EXISTS(SELECT 1 FROM pg_type t WHERE t.oid=ANY(f.proargtypes) AND t.typtype='c') THEN 50 ELSE 25 END,'function',format('%I.%I(%s)',f.nspname,f.proname,pg_get_function_identity_arguments(f.oid)),pg_get_functiondef(f.oid)||';' FROM funcs f
 UNION ALL SELECT 60,'default',c.ident||'.'||a.attname,format('ALTER TABLE %s ALTER COLUMN %I SET DEFAULT %s;',c.ident,a.attname,pg_get_expr(d.adbin,d.adrelid)) FROM rels c JOIN pg_attribute a ON a.attrelid=c.oid JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum WHERE a.attgenerated='' AND a.attidentity=''
 UNION ALL SELECT 65,'sequence-owner',c.ident,format('ALTER SEQUENCE %s OWNED BY %s.%I;',c.ident,format('%I.%I',n.nspname,t.relname),a.attname) FROM rels c JOIN pg_depend d ON d.classid='pg_class'::regclass AND d.objid=c.oid AND d.refclassid='pg_class'::regclass AND d.deptype='a' JOIN pg_class t ON t.oid=d.refobjid JOIN pg_namespace n ON n.oid=t.relnamespace JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=d.refobjsubid WHERE c.relkind='S'
 UNION ALL SELECT 70,'constraint',c.ident||'.'||k.conname,format('ALTER TABLE %s ADD CONSTRAINT %I %s;',c.ident,k.conname,pg_get_constraintdef(k.oid,false)) FROM rels c JOIN pg_constraint k ON k.conrelid=c.oid WHERE k.contype <> 'f'
 UNION ALL SELECT 80,'foreign-key',c.ident||'.'||k.conname,format('ALTER TABLE %s ADD CONSTRAINT %I %s;',c.ident,k.conname,pg_get_constraintdef(k.oid,false)) FROM rels c JOIN pg_constraint k ON k.conrelid=c.oid WHERE k.contype='f'
 UNION ALL SELECT 90,'index',c.ident,pg_get_indexdef(c.oid)||';' FROM rels c WHERE c.relkind='i' AND NOT EXISTS(SELECT 1 FROM pg_constraint k WHERE k.conindid=c.oid)
 UNION ALL SELECT 95,'view',c.ident,format('CREATE VIEW %s%s AS %s;',c.ident,CASE WHEN c.reloptions IS NULL THEN '' ELSE ' WITH ('||array_to_string(c.reloptions,',')||')' END,pg_get_viewdef(c.oid,false)) FROM rels c WHERE c.relkind='v'
 UNION ALL SELECT 100,'trigger',c.ident||'.'||t.tgname,pg_get_triggerdef(t.oid,false)||';'||CASE t.tgenabled WHEN 'D' THEN format('ALTER TABLE %s DISABLE TRIGGER %I;',c.ident,t.tgname) WHEN 'A' THEN format('ALTER TABLE %s ENABLE ALWAYS TRIGGER %I;',c.ident,t.tgname) WHEN 'R' THEN format('ALTER TABLE %s ENABLE REPLICA TRIGGER %I;',c.ident,t.tgname) ELSE '' END FROM rels c JOIN pg_trigger t ON t.tgrelid=c.oid WHERE NOT t.tgisinternal
 UNION ALL SELECT 110,'policy',c.ident||'.'||p.polname,format('CREATE POLICY %I ON %s AS %s FOR %s TO %s%s%s;',p.polname,c.ident,CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,CASE p.polcmd WHEN '*' THEN 'ALL' WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT' WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE' END,(SELECT string_agg(CASE WHEN r=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(r)) END,',' ORDER BY CASE WHEN r=0 THEN 'PUBLIC' ELSE pg_get_userbyid(r) END) FROM unnest(p.polroles) r),CASE WHEN p.polqual IS NOT NULL THEN ' USING ('||pg_get_expr(p.polqual,p.polrelid)||')' ELSE '' END,CASE WHEN p.polwithcheck IS NOT NULL THEN ' WITH CHECK ('||pg_get_expr(p.polwithcheck,p.polrelid)||')' ELSE '' END) FROM rels c JOIN pg_policy p ON p.polrelid=c.oid
 UNION ALL SELECT 120,'rls',c.ident,format('ALTER TABLE %s %s ROW LEVEL SECURITY; ALTER TABLE %s %s FORCE ROW LEVEL SECURITY;',c.ident,CASE WHEN c.relrowsecurity THEN 'ENABLE' ELSE 'DISABLE' END,c.ident,CASE WHEN c.relforcerowsecurity THEN '' ELSE 'NO' END) FROM rels c WHERE c.relkind='r'
 UNION ALL SELECT 125,'table-options',c.ident,format('ALTER TABLE %s REPLICA IDENTITY %s;',c.ident,CASE c.relreplident WHEN 'f' THEN 'FULL' WHEN 'n' THEN 'NOTHING' ELSE 'DEFAULT' END)||CASE WHEN c.reloptions IS NULL THEN '' ELSE format('ALTER TABLE %s SET (%s);',c.ident,array_to_string(c.reloptions,',')) END FROM rels c WHERE c.relkind='r'
 UNION ALL SELECT 130,'owner',c.ident,format('ALTER %s %s OWNER TO %I;',CASE c.relkind WHEN 'S' THEN 'SEQUENCE' WHEN 'v' THEN 'VIEW' ELSE 'TABLE' END,c.ident,pg_get_userbyid(c.relowner)) FROM rels c WHERE c.relkind IN ('r','S','v')
 UNION ALL SELECT 130,'owner',format('%I.%I(%s)',f.nspname,f.proname,pg_get_function_identity_arguments(f.oid)),format('ALTER %s %I.%I(%s) OWNER TO %I;',CASE f.prokind WHEN 'p' THEN 'PROCEDURE' ELSE 'FUNCTION' END,f.nspname,f.proname,pg_get_function_identity_arguments(f.oid),pg_get_userbyid(f.proowner)) FROM funcs f
 UNION ALL SELECT 130,'enum-owner',format('%I.%I',n.nspname,t.typname),format('ALTER TYPE %I.%I OWNER TO %I;',n.nspname,t.typname,pg_get_userbyid(t.typowner)) FROM pg_type t JOIN ns n ON n.oid=t.typnamespace WHERE t.typtype='e'
 UNION ALL SELECT 130,'collation-owner',format('%I.%I',co.nspname,co.collname),format('ALTER COLLATION %I.%I OWNER TO %I;',co.nspname,co.collname,pg_get_userbyid(co.collowner)) FROM collations co
 UNION ALL SELECT 170,'role-membership',pg_get_userbyid(m.roleid)||':'||pg_get_userbyid(m.member)||':'||pg_get_userbyid(m.grantor),format('GRANT %I TO %I WITH ADMIN %s, INHERIT %s, SET %s GRANTED BY %I;',pg_get_userbyid(m.roleid),pg_get_userbyid(m.member),m.admin_option::text,m.inherit_option::text,m.set_option::text,pg_get_userbyid(m.grantor)) FROM pg_auth_members m
 UNION ALL SELECT 131,'schema-owner',n.nspname,format('ALTER SCHEMA %I OWNER TO %I;',n.nspname,pg_get_userbyid(s.nspowner)) FROM ns n JOIN pg_namespace s USING(oid)
), permissions AS (
 SELECT 'FUNCTION' kind,format('%I.%I(%s)',f.nspname,f.proname,pg_get_function_identity_arguments(f.oid)) ident,coalesce(f.proacl,acldefault('f',f.proowner)) acl FROM funcs f
 UNION ALL SELECT CASE WHEN c.relkind='S' THEN 'SEQUENCE' ELSE 'TABLE' END,c.ident,coalesce(c.relacl,acldefault(CASE WHEN c.relkind='S' THEN 's'::"char" ELSE 'r'::"char" END,c.relowner)) FROM rels c WHERE c.relkind IN ('r','S','v')
 UNION ALL SELECT 'TYPE',format('%I.%I',n.nspname,t.typname),coalesce(t.typacl,acldefault('T',t.typowner)) FROM pg_type t JOIN ns n ON n.oid=t.typnamespace WHERE t.typtype='e'
 UNION ALL SELECT 'SCHEMA',quote_ident(n.nspname),coalesce(s.nspacl,acldefault('n',s.nspowner)) FROM ns n JOIN pg_namespace s USING(oid)
), grants AS (
 SELECT 140 phase,'revoke' kind,ident identity,format('REVOKE ALL ON %s %s FROM PUBLIC;',kind,ident) ddl FROM permissions
 UNION ALL SELECT 150,'grant',p.ident||':'||pg_get_userbyid(a.grantee)||':'||a.privilege_type,format('GRANT %s ON %s %s TO %s%s;',a.privilege_type,p.kind,p.ident,CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(a.grantee)) END,CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END) FROM permissions p CROSS JOIN LATERAL aclexplode(p.acl) a
 UNION ALL SELECT 155,'default-acl-reset',pg_get_userbyid(d.defaclrole)||':'||coalesce((SELECT nspname FROM pg_namespace WHERE oid=d.defaclnamespace),'')||':'||d.defaclobjtype::text,format('ALTER DEFAULT PRIVILEGES FOR ROLE %I%s REVOKE ALL ON %s FROM PUBLIC;',pg_get_userbyid(d.defaclrole),CASE WHEN d.defaclnamespace=0 THEN '' ELSE ' IN SCHEMA '||quote_ident((SELECT nspname FROM pg_namespace WHERE oid=d.defaclnamespace)) END,CASE d.defaclobjtype WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS' WHEN 'T' THEN 'TYPES' WHEN 'n' THEN 'SCHEMAS' END) FROM pg_default_acl d WHERE d.defaclnamespace=0 OR d.defaclnamespace IN (SELECT oid FROM ns)
 UNION ALL SELECT 160,'default-acl',pg_get_userbyid(d.defaclrole)||':'||coalesce((SELECT nspname FROM pg_namespace WHERE oid=d.defaclnamespace),'')||':'||d.defaclobjtype::text||':'||pg_get_userbyid(a.grantee)||':'||a.privilege_type,format('ALTER DEFAULT PRIVILEGES FOR ROLE %I%s GRANT %s ON %s TO %s%s;',pg_get_userbyid(d.defaclrole),CASE WHEN d.defaclnamespace=0 THEN '' ELSE ' IN SCHEMA '||quote_ident((SELECT nspname FROM pg_namespace WHERE oid=d.defaclnamespace)) END,a.privilege_type,CASE d.defaclobjtype WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS' WHEN 'T' THEN 'TYPES' WHEN 'n' THEN 'SCHEMAS' END,CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(a.grantee)) END,CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END) FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) a WHERE d.defaclnamespace=0 OR d.defaclnamespace IN (SELECT oid FROM ns)
)
SELECT jsonb_build_object(
 'serverVersion',current_setting('server_version'),
 'capturedAt',clock_timestamp(),
 'objects',(SELECT jsonb_agg(x ORDER BY phase,identity) FROM (SELECT * FROM objects UNION ALL SELECT * FROM grants) x),
 'extensions',(SELECT jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname)) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'inherit',rolinherit,'bypassRls',rolbypassrls,'superuser',rolsuper,'createDb',rolcreatedb,'createRole',rolcreaterole,'replication',rolreplication)) FROM pg_roles WHERE rolname NOT LIKE 'pg_%'),
 'history',(SELECT jsonb_agg(jsonb_build_object('version',version,'name',name) ORDER BY version) FROM supabase_migrations.schema_migrations),
 'unsupported',(SELECT coalesce(jsonb_agg(x),'[]'::jsonb) FROM (
 SELECT 'relation-kind' reason,ident identity FROM rels WHERE relkind NOT IN ('r','S','i','v')

 UNION ALL SELECT 'collation-provider',format('%I.%I',co.nspname,co.collname) FROM collations co WHERE co.collprovider NOT IN ('i','c','b')
 UNION ALL SELECT 'inheritance',c.ident FROM rels c JOIN pg_inherits i ON i.inhrelid=c.oid
 UNION ALL SELECT 'domain-range-composite',format('%I.%I',n.nspname,t.typname) FROM pg_type t JOIN ns n ON n.oid=t.typnamespace WHERE (t.typtype IN ('d','r','m') OR (t.typtype='c' AND NOT EXISTS(SELECT 1 FROM rels c WHERE c.oid=t.typrelid AND c.relkind='r'))) AND NOT EXISTS(SELECT 1 FROM ext e WHERE (e.classid='pg_type'::regclass AND e.objid=t.oid) OR (e.classid='pg_class'::regclass AND e.objid=t.typrelid))
 UNION ALL SELECT 'column-acl',c.ident||'.'||a.attname FROM rels c JOIN pg_attribute a ON a.attrelid=c.oid WHERE a.attacl IS NOT NULL
 UNION ALL SELECT 'replica-identity-index',c.ident FROM rels c WHERE c.relreplident='i'

 ) x),
 'externalDependencies',(SELECT coalesce(jsonb_agg(DISTINCT jsonb_build_object('type',a.type,'schema',a.schema,'identity',a.identity)),'[]'::jsonb) FROM pg_depend d CROSS JOIN LATERAL pg_identify_object(d.refclassid,d.refobjid,d.refobjsubid) a WHERE ((d.classid='pg_class'::regclass AND d.objid IN (SELECT oid FROM rels)) OR (d.classid='pg_proc'::regclass AND d.objid IN (SELECT oid FROM funcs)) OR (d.classid='pg_constraint'::regclass AND d.objid IN (SELECT oid FROM pg_constraint WHERE conrelid IN (SELECT oid FROM rels))) OR (d.classid='pg_attrdef'::regclass AND d.objid IN (SELECT oid FROM pg_attrdef WHERE adrelid IN (SELECT oid FROM rels)))) AND a.schema IS NOT NULL AND a.schema NOT IN ('pg_catalog','public','sellerpilot_private','auth','storage','extensions') AND NOT EXISTS(SELECT 1 FROM ext e WHERE e.classid=d.refclassid AND e.objid=d.refobjid))
) AS package;
